character_names = [
    "0-0-0",
    "50R-T",
    "ARC Trooper",
    "Aayla Secura",
    "Admiral Ackbar",
    "Admiral Piett",
    "Admiral Raddus",
    "Admiral Trench",
    "Ahsoka Tano",
    "Ahsoka Tano (Fulcrum)",
    "Ahsoka Tano (Snips)",
    "Amilyn Holdo",
    "Asajj Ventress",
    "Aurra Sing",
    "B1 Battle Droid",
    "B2 Super Battle Droid",
    "BB-8",
    "BT-1",
    "Barriss Offee",
    "Bastila Shan",
    "Bastila Shan (Fallen)",
    "Batcher",
    "Baylan Skoll",
    "Baze Malbus",
    "Ben Solo",
    "Biggs Darklighter",
    "Bistan",
    "Bo-Katan (Mand'alor)",
    "Bo-Katan Kryze",
    "Boba Fett",
    "Boba Fett, Scion of Jango",
    "Bodhi Rook",
    "Boss Nass",
    "Bossk",
    "Boushh (Leia Organa)",
    "C-3PO",
    "CC-1119 \"Appo\"",
    "CC-2224 \"Cody\"",
    "CT-21-0408 \"Echo\"",
    "CT-5555 \"Fives\"",
    "CT-7567 \"Rex\"",
    "CX-2",
    "Cad Bane",
    "Cal Kestis",
    "Canderous Ordo",
    "Captain Drogan",
    "Captain Enoch",
    "Captain Han Solo",
    "Captain Phasma",
    "Captain Rex",
    "Captain Tarpals",
    "Cara Dune",
    "Carth Onasi",
    "Cassian Andor",
    "Cere Junda",
    "Chewbacca",
    "Chief Chirpa",
    "Chief Nebit",
    "Chirrut Îmwe",
    "Chopper",
    "Clone Sergeant - Phase I",
    "Clone Wars Chewbacca",
    "Colonel Starck",
    "Commander Ahsoka Tano",
    "Commander Luke Skywalker",
    "Coruscant Underworld Police",
    "Count Dooku",
    "Crosshair (Scarred)",
    "Dark Trooper",
    "Dark Trooper Moff Gideon",
    "Darth Bane",
    "Darth Malak",
    "Darth Malgus",
    "Darth Maul",
    "Darth Nihilus",
    "Darth Revan",
    "Darth Sidious",
    "Darth Sion",
    "Darth Talon",
    "Darth Traya",
    "Darth Vader",
    "Dash Rendar",
    "Dathcha",
    "Death Trooper",
    "Death Trooper (Peridea)",
    "Dengar",
    "Director Krennic",
    "Disguised Clone Trooper",
    "Doctor Aphra",
    "Droideka",
    "Echo",
    "Eeth Koth",
    "Eighth Brother",
    "Embo",
    "Emperor Palpatine",
    "Enfys Nest",
    "Ewok Elder",
    "Ewok Scout",
    "Ezra Bridger",
    "Ezra Bridger (Exile)",
    "Fennec Shand",
    "Fifth Brother",
    "Finn",
    "First Order Executioner",
    "First Order Officer",
    "First Order SF TIE Pilot",
    "First Order Stormtrooper",
    "First Order TIE Pilot",
    "Gamorrean Guard",
    "Gar Saxon",
    "Garazeb \"Zeb\" Orrelios",
    "General Grievous",
    "General Hux",
    "General Kenobi",
    "General Skywalker",
    "General Syndulla",
    "General Veers",
    "Geonosian Brood Alpha",
    "Geonosian Soldier",
    "Geonosian Spy",
    "Grand Admiral Thrawn",
    "Grand Inquisitor",
    "Grand Master Yoda",
    "Grand Moff Tarkin",
    "Great Mothers",
    "Greedo",
    "Greef Karga",
    "Gungan Boomadier",
    "Gungan Phalanx",
    "HK-47",
    "Han Solo",
    "Hera Syndulla",
    "Hermit Yoda",
    "Hondo Ohnaka",
    "Hoth Rebel Scout",
    "Hoth Rebel Soldier",
    "Hunter",
    "Hunter (Mercenary)",
    "Huyang",
    "IG-100 MagnaGuard",
    "IG-11",
    "IG-12 & Grogu",
    "IG-86 Sentinel Droid",
    "IG-88",
    "Iden Versio",
    "Ima-Gun Di",
    "Imperial Probe Droid",
    "Imperial Super Commando",
    "Jabba the Hutt",
    "Jango Fett",
    "Jar Jar Binks",
    "Jawa",
    "Jawa Engineer",
    "Jawa Scavenger",
    "Jedi Consular",
    "Jedi Knight Anakin",
    "Jedi Knight Cal Kestis",
    "Jedi Knight Guardian",
    "Jedi Knight Luke Skywalker",
    "Jedi Knight Revan",
    "Jedi Master Kenobi",
    "Jedi Master Luke Skywalker",
    "Jocasta Nu",
    "Jolee Bindo",
    "Juhani",
    "Jyn Erso",
    "K-2SO",
    "Kanan Jarrus",
    "Kelleran Beq",
    "Ki-Adi-Mundi",
    "Kit Fisto",
    "Krrsantan",
    "Kuiil",
    "Kyle Katarn",
    "Kylo Ren",
    "Kylo Ren (Unmasked)",
    "L3-37",
    "Lando Calrissian",
    "Leia Organa",
    "Lobot",
    "Logray",
    "Lord Vader",
    "Luke Skywalker (Farmboy)",
    "Luminara Unduli",
    "Luthen Rael",
    "Mace Windu",
    "Magmatrooper",
    "Mara Jade, The Emperor's Hand",
    "Marrok",
    "Master Qui-Gon",
    "Maul",
    "Merrin",
    "Mission Vao",
    "Mob Enforcer",
    "Moff Gideon",
    "Mon Mothma",
    "Morgan Elsbeth",
    "Mother Talzin",
    "Night Trooper",
    "Nightsister Acolyte",
    "Nightsister Initiate",
    "Nightsister Spirit",
    "Nightsister Zombie",
    "Ninth Sister",
    "Nute Gunray",
    "Obi-Wan Kenobi (Old Ben)",
    "Old Daka",
    "Omega",
    "Omega (Fugitive)",
    "Padawan Obi-Wan",
    "Padawan Sabine Wren",
    "Padmé Amidala",
    "Pao",
    "Paploo",
    "Paz Vizsla",
    "Plo Koon",
    "Poe Dameron",
    "Poggle the Lesser",
    "Princess Kneesaa",
    "Princess Leia",
    "Qi'ra",
    "Queen Amidala",
    "Qui-Gon Jinn",
    "R2-D2",
    "RC-1262 \"Scorch\"",
    "Range Trooper",
    "Rebel Officer Leia Organa",
    "Resistance Hero Finn",
    "Resistance Hero Poe",
    "Resistance Pilot",
    "Resistance Trooper",
    "Rey",
    "Rey (Dark Side Vision)",
    "Rey (Jedi Training)",
    "Rey (Scavenger)",
    "Rose Tico",
    "Royal Guard",
    "SM-33",
    "STAP",
    "Sabine Wren",
    "Sana Starros",
    "Savage Opress",
    "Saw Gerrera",
    "Scarif Rebel Pathfinder",
    "Scout Trooper",
    "Second Sister",
    "Seventh Sister",
    "Shaak Ti",
    "Shin Hati",
    "Shoretrooper",
    "Sith Assassin",
    "Sith Empire Trooper",
    "Sith Eternal Emperor",
    "Sith Marauder",
    "Sith Trooper",
    "Skiff Guard (Lando Calrissian)",
    "Snowtrooper",
    "Starkiller",
    "Stormtrooper",
    "Stormtrooper Han",
    "Sun Fac",
    "Supreme Leader Kylo Ren",
    "T3-M4",
    "TIE Fighter Pilot",
    "Talia",
    "Tarfful",
    "Taron Malicos",
    "Tech",
    "Teebo",
    "The Armorer",
    "The Mandalorian",
    "The Mandalorian (Beskar Armor)",
    "Third Sister",
    "Threepio & Chewie",
    "Tusken Chieftain",
    "Tusken Raider",
    "Tusken Shaman",
    "Tusken Warrior",
    "URoRRuR'R'R",
    "Ugnaught",
    "Vandor Chewbacca",
    "Veteran Smuggler Chewbacca",
    "Veteran Smuggler Han Solo",
    "Visas Marr",
    "Wampa",
    "Wat Tambor",
    "Wedge Antilles",
    "Wicket",
    "Wrecker",
    "Wrecker (Mercenary)",
    "Young Han Solo",
    "Young Lando Calrissian",
    "Zaalbar",
    "Zam Wesell",
    "Zorii Bliss",
]

Salvage = ["Carbonite circuit board", "Bronzium wiring", "Chromium transistor", "Aurodium heatsink",
           "Electrium conductor", "Zinbiddle card", "Impulse detector", "Aeromagnifier",
           "Gyrda keypad", "Droid brain"]

Signal_Data = ["Fragmented [light blue]",
               "Incomplete [green]",
               "Flawed [dark blue]"]

salvage_reqs = [
    [40, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # R0
    [30, 40, 0, 0, 0, 0, 0, 0, 0, 0],  # R1
    [30, 40, 0, 0, 0, 0, 0, 0, 0, 0],  # R2
    [30, 40, 40, 0, 0, 0, 0, 0, 0, 0],  # R3
    [30, 40, 30, 20, 0, 0, 0, 0, 0, 0],  # R4
    [20, 30, 30, 20, 20, 0, 0, 0, 0, 0],  # R5
    [20, 30, 20, 20, 20, 10, 0, 0, 0, 0],  # R6
    [0, 0, 20, 20, 20, 20, 20, 20, 0, 0],  # R7
    [0, 0, 20, 20, 20, 20, 20, 20, 20, 20],  # R8
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # R9
]

signalData_reqs = [
    [0, 0, 0], [15, 0, 0], [20, 15, 0], [20, 25, 0],
    [20, 25, 15], [20, 25, 25], [20, 25, 35], [20, 25, 45],
    [30, 30, 55], [0, 0, 0]
    ]

status_effects = {
    "Ability Block": [
        "Admiral Trench", "BT-1", "Bastila Shan", "Bastila Shan (Fallen)", "Batcher",
        "Boba Fett", "Boba Fett, Scion of Jango", "Boushh (Leia Organa)", "Cal Kestis", "Captain Drogan",
        "Captain Rex", "Cassian Andor", "Cere Junda", "Chewbacca", "Count Dooku",
        "Darth Bane", "Darth Malgus", "Darth Revan", "Darth Talon", "Darth Traya",
        "Darth Vader", "Dathcha", "Director Krennic", "Disguised Clone Trooper", "Doctor Aphra",
        "Eeth Koth", "Eighth Brother", "Ezra Bridger (Exile)", "General Veers", "Grand Admiral Thrawn",
        "Grand Inquisitor", "Great Mothers", "Gungan Boomadier", "Hondo Ohnaka", "IG-12 & Grogu",
        "IG-88", "Jedi Knight Cal Kestis", "Jedi Knight Guardian", "Jedi Knight Revan", "Jedi Master Kenobi",
        "Jedi Master Luke Skywalker", "Jocasta Nu", "Krrsantan", "Kyle Katarn", "Lord Vader",
        "Luminara Unduli", "Luthen Rael", "Mace Windu", "Marrok", "Master Qui-Gon",
        "Maul", "Ninth Sister", "Obi-Wan Kenobi (Old Ben)", "Poggle the Lesser", "Rebel Officer Leia Organa",
        "Rey (Jedi Training)", "SM-33", "Seventh Sister", "Sith Eternal Emperor", "Snowtrooper",
        "T3-M4", "TIE Fighter Pilot", "The Mandalorian (Beskar Armor)", "Third Sister", "Veteran Smuggler Han Solo",
        "Young Lando Calrissian",
    ],
    "Accuracy Down": [
        "Cad Bane", "Doctor Aphra", "Eighth Brother", "Padawan Obi-Wan", "Scout Trooper",
        "Seventh Sister",
    ],
    "Accuracy Up": [
        "Bastila Shan", "Cal Kestis", "Cere Junda", "Dark Trooper Moff Gideon", "Eighth Brother",
        "Gungan Boomadier", "Master Qui-Gon", "Padawan Obi-Wan", "Queen Amidala", "Scarif Rebel Pathfinder",
        "Scout Trooper", "Taron Malicos",
    ],
    "Advantage": [
        "50R-T", "Admiral Trench", "BB-8", "Bastila Shan", "Bastila Shan (Fallen)",
        "CC-1119 \"Appo\"", "Cad Bane", "Captain Enoch", "Captain Phasma", "Captain Tarpals",
        "Cere Junda", "Commander Ahsoka Tano", "Dark Trooper", "Darth Maul", "Disguised Clone Trooper",
        "Finn", "First Order Executioner", "First Order Officer", "First Order SF TIE Pilot", "First Order Stormtrooper",
        "First Order TIE Pilot", "General Hux", "General Kenobi", "Grand Inquisitor", "Huyang",
        "Jabba the Hutt", "Jedi Knight Anakin", "Jedi Knight Cal Kestis", "Jedi Knight Revan", "Jedi Master Luke Skywalker",
        "Jyn Erso", "Kylo Ren", "Kylo Ren (Unmasked)", "Logray", "Luke Skywalker (Farmboy)",
        "Marrok", "Master Qui-Gon", "Omega (Fugitive)", "Queen Amidala", "R2-D2",
        "Rey (Dark Side Vision)", "Scout Trooper", "Seventh Sister", "Sith Trooper", "Supreme Leader Kylo Ren",
        "Tarfful", "Threepio & Chewie", "Vandor Chewbacca",
    ],
    "Alert": [
        "Night Trooper",
    ],
    "Anti-Droid": [
        "Eeth Koth", "Ima-Gun Di",
    ],
    "Anti-Revive": [
        "Admiral Raddus", "Ahsoka Tano (Fulcrum)", "Baylan Skoll", "Boba Fett", "Boushh (Leia Organa)",
        "CT-5555 \"Fives\"", "Dark Trooper", "Darth Bane", "Darth Nihilus", "Death Trooper",
        "General Skywalker", "Grand Inquisitor", "Grand Moff Tarkin", "Great Mothers", "Gungan Boomadier",
        "Imperial Probe Droid", "Jedi Knight Cal Kestis", "Jocasta Nu", "Marrok", "Morgan Elsbeth",
        "Mother Talzin", "Omega (Fugitive)", "Qui-Gon Jinn", "Rey", "Rey (Dark Side Vision)",
        "SM-33", "Sith Eternal Emperor", "Supreme Leader Kylo Ren", "Taron Malicos", "The Mandalorian",
        "The Mandalorian (Beskar Armor)", "Wat Tambor",
    ],
    "AoE": [
        "0-0-0", "50R-T", "Admiral Piett", "Admiral Raddus", "Amilyn Holdo",
        "Asajj Ventress", "B1 Battle Droid", "B2 Super Battle Droid", "BB-8", "BT-1",
        "Bastila Shan (Fallen)", "Batcher", "Baylan Skoll", "Baze Malbus", "Ben Solo",
        "Bo-Katan Kryze", "Boba Fett", "Boba Fett, Scion of Jango", "Bodhi Rook", "Boss Nass",
        "Boushh (Leia Organa)", "CC-1119 \"Appo\"", "CT-21-0408 \"Echo\"", "Cad Bane", "Cal Kestis",
        "Canderous Ordo", "Captain Enoch", "Captain Phasma", "Captain Rex", "Captain Tarpals",
        "Cara Dune", "Carth Onasi", "Chewbacca", "Chopper", "Clone Sergeant - Phase I",
        "Colonel Starck", "Coruscant Underworld Police", "Dark Trooper", "Dark Trooper Moff Gideon", "Darth Bane",
        "Darth Malgus", "Darth Maul", "Darth Nihilus", "Darth Revan", "Darth Sidious",
        "Darth Sion", "Darth Talon", "Darth Vader", "Dash Rendar", "Dathcha",
        "Death Trooper", "Death Trooper (Peridea)", "Dengar", "Director Krennic", "Disguised Clone Trooper",
        "Doctor Aphra", "Echo", "Eighth Brother", "Emperor Palpatine", "Enfys Nest",
        "Ezra Bridger (Exile)", "Fifth Brother", "First Order SF TIE Pilot", "Gar Saxon", "General Grievous",
        "General Hux", "General Skywalker", "General Syndulla", "General Veers", "Geonosian Brood Alpha",
        "Geonosian Spy", "Grand Inquisitor", "Grand Master Yoda", "Grand Moff Tarkin", "Great Mothers",
        "Greedo", "Gungan Boomadier", "Gungan Phalanx", "HK-47", "Hondo Ohnaka",
        "Hunter", "Hunter (Mercenary)", "IG-100 MagnaGuard", "IG-11", "IG-12 & Grogu",
        "IG-88", "Iden Versio", "Imperial Probe Droid", "Jabba the Hutt", "Jango Fett",
        "Jar Jar Binks", "Jawa", "Jawa Scavenger", "Jedi Knight Anakin", "Jedi Knight Cal Kestis",
        "Jedi Knight Guardian", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker",
        "Jocasta Nu", "Juhani", "Jyn Erso", "Ki-Adi-Mundi", "Kit Fisto",
        "Krrsantan", "Kyle Katarn", "Kylo Ren", "Lando Calrissian", "Leia Organa",
        "Logray", "Lord Vader", "Mace Windu", "Magmatrooper", "Mara Jade, The Emperor's Hand",
        "Marrok", "Master Qui-Gon", "Maul", "Merrin", "Moff Gideon",
        "Morgan Elsbeth", "Mother Talzin", "Night Trooper", "Ninth Sister", "Nute Gunray",
        "Obi-Wan Kenobi (Old Ben)", "Omega (Fugitive)", "Padawan Obi-Wan", "Padawan Sabine Wren", "Pao",
        "Paz Vizsla", "Plo Koon", "Princess Kneesaa", "Qi'ra", "Queen Amidala",
        "R2-D2", "RC-1262 \"Scorch\"", "Resistance Hero Finn", "Rey", "Rey (Dark Side Vision)",
        "STAP", "Sabine Wren", "Sana Starros", "Saw Gerrera", "Scarif Rebel Pathfinder",
        "Scout Trooper", "Shin Hati", "Sith Empire Trooper", "Sith Eternal Emperor", "Sith Trooper",
        "Snowtrooper", "Starkiller", "Supreme Leader Kylo Ren", "T3-M4", "TIE Fighter Pilot",
        "Tarfful", "Taron Malicos", "Tech", "The Mandalorian (Beskar Armor)", "Third Sister",
        "Threepio & Chewie", "Tusken Warrior", "Ugnaught", "Vandor Chewbacca", "Veteran Smuggler Chewbacca",
        "Veteran Smuggler Han Solo", "Visas Marr", "Wampa", "Wedge Antilles", "Wicket",
        "Wrecker", "Wrecker (Mercenary)", "Zaalbar", "Zam Wesell", "Zorii Bliss",
    ],
    "Armor Shred": [
        "Ahsoka Tano", "Baylan Skoll", "Ben Solo", "Bo-Katan (Mand'alor)", "Boba Fett, Scion of Jango",
        "Captain Rex", "Commander Ahsoka Tano", "Crosshair (Scarred)", "Death Trooper (Peridea)", "Doctor Aphra",
        "Eighth Brother", "Fennec Shand", "General Skywalker", "Jedi Knight Cal Kestis", "Ki-Adi-Mundi",
        "Moff Gideon", "Morgan Elsbeth", "Sabine Wren", "Skiff Guard (Lando Calrissian)", "The Armorer",
        "Third Sister", "Zaalbar",
    ],
    "Assist": [
        "ARC Trooper", "Aayla Secura", "Admiral Ackbar", "Admiral Piett", "Admiral Raddus",
        "Admiral Trench", "Ahsoka Tano (Snips)", "B1 Battle Droid", "BB-8", "BT-1",
        "Bastila Shan", "Batcher", "Baylan Skoll", "Baze Malbus", "Biggs Darklighter",
        "Bo-Katan (Mand'alor)", "Bo-Katan Kryze", "Bodhi Rook", "Boss Nass", "Bossk",
        "Boushh (Leia Organa)", "C-3PO", "CC-1119 \"Appo\"", "CC-2224 \"Cody\"", "CT-21-0408 \"Echo\"",
        "CT-5555 \"Fives\"", "Captain Drogan", "Captain Enoch", "Captain Phasma", "Captain Rex",
        "Captain Tarpals", "Carth Onasi", "Cassian Andor", "Chewbacca", "Chief Chirpa",
        "Chief Nebit", "Chirrut Îmwe", "Chopper", "Commander Ahsoka Tano", "Crosshair (Scarred)",
        "Dark Trooper Moff Gideon", "Darth Revan", "Dash Rendar", "Dengar", "Director Krennic",
        "Doctor Aphra", "Droideka", "Echo", "Ewok Elder", "Ewok Scout",
        "Ezra Bridger", "Ezra Bridger (Exile)", "First Order SF TIE Pilot", "First Order Stormtrooper", "Gamorrean Guard",
        "Gar Saxon", "General Hux", "General Kenobi", "General Syndulla", "General Veers",
        "Geonosian Brood Alpha", "Geonosian Soldier", "Grand Moff Tarkin", "Great Mothers", "Greef Karga",
        "Gungan Phalanx", "Hera Syndulla", "Hermit Yoda", "Hondo Ohnaka", "Hunter (Mercenary)",
        "Huyang", "IG-11", "IG-12 & Grogu", "IG-86 Sentinel Droid", "Iden Versio",
        "Jabba the Hutt", "Jar Jar Binks", "Jedi Knight Cal Kestis", "Jedi Knight Luke Skywalker", "Jedi Knight Revan",
        "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jolee Bindo", "Juhani", "K-2SO",
        "Kelleran Beq", "Kyle Katarn", "Leia Organa", "Lobot", "Logray",
        "Luthen Rael", "Mace Windu", "Mara Jade, The Emperor's Hand", "Marrok", "Master Qui-Gon",
        "Maul", "Mission Vao", "Moff Gideon", "Mon Mothma", "Morgan Elsbeth",
        "Mother Talzin", "Night Trooper", "Nute Gunray", "Omega", "Padawan Obi-Wan",
        "Padmé Amidala", "Paploo", "Poggle the Lesser", "Princess Kneesaa", "Qi'ra",
        "Queen Amidala", "Qui-Gon Jinn", "RC-1262 \"Scorch\"", "Range Trooper", "Resistance Hero Finn",
        "Rey (Dark Side Vision)", "Rey (Jedi Training)", "SM-33", "STAP", "Sana Starros",
        "Saw Gerrera", "Scout Trooper", "Seventh Sister", "Shaak Ti", "Shin Hati",
        "Sith Eternal Emperor", "Sith Trooper", "Skiff Guard (Lando Calrissian)", "Starkiller", "Tarfful",
        "Taron Malicos", "The Armorer", "The Mandalorian", "The Mandalorian (Beskar Armor)", "Threepio & Chewie",
        "Tusken Chieftain", "Tusken Raider", "Visas Marr", "Wat Tambor", "Wicket",
        "Young Han Solo", "Zaalbar", "Zorii Bliss",
    ],
    "Blight": [
        "Captain Enoch", "Death Trooper (Peridea)", "Night Trooper",
    ],
    "Blind": [
        "Baylan Skoll", "Ben Solo", "Darth Malgus", "Eighth Brother", "Ezra Bridger (Exile)",
        "General Syndulla", "IG-12 & Grogu", "Jabba the Hutt", "Jar Jar Binks", "Jedi Knight Luke Skywalker",
        "Mara Jade, The Emperor's Hand", "Mission Vao", "Morgan Elsbeth", "Omega", "Saw Gerrera",
        "Sun Fac", "Threepio & Chewie",
    ],
    "Bonus Attack": [
        "Boba Fett", "Boushh (Leia Organa)", "CT-5555 \"Fives\"", "Cad Bane", "Cal Kestis",
        "Canderous Ordo", "Count Dooku", "Darth Malgus", "Darth Revan", "Death Trooper",
        "Ezra Bridger", "Ezra Bridger (Exile)", "First Order TIE Pilot", "Grand Inquisitor", "Greedo",
        "Hunter", "Imperial Super Commando", "Kelleran Beq", "Ki-Adi-Mundi", "Kit Fisto",
        "Princess Leia", "Rey (Dark Side Vision)", "Rose Tico", "Shaak Ti", "Shin Hati",
        "Skiff Guard (Lando Calrissian)", "Tech", "Tusken Warrior", "Veteran Smuggler Han Solo", "Wrecker",
    ],
    "Bonus Turn": [
        "Admiral Raddus", "Admiral Trench", "Ahsoka Tano", "Aurra Sing", "BT-1",
        "Baylan Skoll", "Bo-Katan (Mand'alor)", "Boba Fett", "Boss Nass", "C-3PO",
        "Captain Tarpals", "Cassian Andor", "Crosshair (Scarred)", "Dark Trooper Moff Gideon", "Darth Bane",
        "Darth Malak", "Darth Malgus", "Darth Vader", "Death Trooper (Peridea)", "Disguised Clone Trooper",
        "Embo", "Emperor Palpatine", "Ezra Bridger (Exile)", "Fifth Brother", "First Order TIE Pilot",
        "General Grievous", "General Hux", "General Skywalker", "General Syndulla", "Grand Admiral Thrawn",
        "Grand Inquisitor", "Grand Master Yoda", "Great Mothers", "HK-47", "Han Solo",
        "Hondo Ohnaka", "Hunter (Mercenary)", "IG-100 MagnaGuard", "IG-12 & Grogu", "Jabba the Hutt",
        "Jango Fett", "Jar Jar Binks", "Jedi Knight Anakin", "Jedi Knight Cal Kestis", "Jedi Knight Revan",
        "Jocasta Nu", "Kelleran Beq", "Kyle Katarn", "Leia Organa", "Lobot",
        "Lord Vader", "Luthen Rael", "Master Qui-Gon", "Maul", "Mob Enforcer",
        "Night Trooper", "Ninth Sister", "Omega (Fugitive)", "Padawan Obi-Wan", "Padmé Amidala",
        "Paz Vizsla", "Princess Kneesaa", "Queen Amidala", "Rey", "Rey (Dark Side Vision)",
        "SM-33", "STAP", "Sana Starros", "Saw Gerrera", "Shin Hati",
        "Sith Eternal Emperor", "Sith Trooper", "Skiff Guard (Lando Calrissian)", "Starkiller", "Supreme Leader Kylo Ren",
        "Taron Malicos", "The Mandalorian (Beskar Armor)", "Tusken Chieftain", "Tusken Warrior", "Veteran Smuggler Chewbacca",
        "Veteran Smuggler Han Solo", "Wat Tambor", "Wrecker (Mercenary)", "Young Lando Calrissian", "Zaalbar",
        "Zorii Bliss",
    ],
    "Breach": [
        "Boba Fett, Scion of Jango", "Doctor Aphra", "Fifth Brother", "Jedi Master Luke Skywalker", "Jocasta Nu",
        "Master Qui-Gon", "Paz Vizsla", "STAP",
    ],
    "Buff Immunity": [
        "Admiral Trench", "B2 Super Battle Droid", "Bastila Shan", "Baylan Skoll", "Cal Kestis",
        "Captain Tarpals", "Cassian Andor", "Commander Luke Skywalker", "Darth Revan", "Darth Talon",
        "Director Krennic", "Doctor Aphra", "Echo", "Eighth Brother", "Enfys Nest",
        "Ezra Bridger (Exile)", "First Order TIE Pilot", "General Syndulla", "Grand Inquisitor", "Hondo Ohnaka",
        "Hunter (Mercenary)", "Imperial Super Commando", "Jabba the Hutt", "Jedi Knight Anakin", "Jedi Knight Revan",
        "Jedi Master Luke Skywalker", "Jyn Erso", "Leia Organa", "Lord Vader", "Luthen Rael",
        "Master Qui-Gon", "Maul", "Morgan Elsbeth", "Nightsister Initiate", "Padawan Obi-Wan",
        "Poe Dameron", "Rebel Officer Leia Organa", "Resistance Hero Poe", "SM-33", "Shin Hati",
        "Starkiller", "Supreme Leader Kylo Ren", "TIE Fighter Pilot", "Taron Malicos",
    ],
    "Burning": [
        "Admiral Trench", "BT-1", "Captain Drogan", "Eighth Brother", "Jango Fett",
        "Jocasta Nu", "Kuiil", "Leia Organa", "Paz Vizsla", "R2-D2",
        "SM-33", "Saw Gerrera",
    ],
    "Counter": [
        "0-0-0", "50R-T", "ARC Trooper", "Aayla Secura", "Admiral Piett",
        "Admiral Raddus", "Admiral Trench", "Ahsoka Tano", "Ahsoka Tano (Fulcrum)", "Ahsoka Tano (Snips)",
        "Asajj Ventress", "Aurra Sing", "BB-8", "Bastila Shan", "Bastila Shan (Fallen)",
        "Batcher", "Baylan Skoll", "Baze Malbus", "Ben Solo", "Bo-Katan (Mand'alor)",
        "Bo-Katan Kryze", "Boba Fett", "Boba Fett, Scion of Jango", "Boss Nass", "Boushh (Leia Organa)",
        "C-3PO", "CC-1119 \"Appo\"", "CT-5555 \"Fives\"", "CT-7567 \"Rex\"", "CX-2",
        "Cal Kestis", "Captain Drogan", "Captain Enoch", "Captain Phasma", "Captain Rex",
        "Captain Tarpals", "Carth Onasi", "Cassian Andor", "Cere Junda", "Chief Chirpa",
        "Chirrut Îmwe", "Commander Ahsoka Tano", "Commander Luke Skywalker", "Count Dooku", "Crosshair (Scarred)",
        "Dark Trooper Moff Gideon", "Darth Bane", "Darth Malak", "Darth Malgus", "Darth Maul",
        "Darth Nihilus", "Darth Sidious", "Darth Talon", "Darth Traya", "Darth Vader",
        "Death Trooper (Peridea)", "Dengar", "Disguised Clone Trooper", "Doctor Aphra", "Droideka",
        "Eighth Brother", "Embo", "Emperor Palpatine", "Enfys Nest", "Ezra Bridger",
        "Fennec Shand", "Fifth Brother", "Finn", "First Order Executioner", "First Order Stormtrooper",
        "First Order TIE Pilot", "Gamorrean Guard", "Gar Saxon", "Garazeb \"Zeb\" Orrelios", "General Grievous",
        "General Hux", "General Kenobi", "General Skywalker", "General Syndulla", "Geonosian Brood Alpha",
        "Geonosian Spy", "Grand Admiral Thrawn", "Grand Inquisitor", "Grand Moff Tarkin", "Great Mothers",
        "Greedo", "Greef Karga", "Gungan Boomadier", "Gungan Phalanx", "HK-47",
        "Han Solo", "Hera Syndulla", "Hermit Yoda", "Hondo Ohnaka", "Hoth Rebel Soldier",
        "Hunter", "Hunter (Mercenary)", "IG-100 MagnaGuard", "IG-11", "IG-12 & Grogu",
        "Iden Versio", "Ima-Gun Di", "Imperial Probe Droid", "Imperial Super Commando", "Jabba the Hutt",
        "Jango Fett", "Jar Jar Binks", "Jedi Knight Cal Kestis", "Jedi Knight Luke Skywalker", "Jedi Knight Revan",
        "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jocasta Nu", "Juhani", "K-2SO",
        "Kanan Jarrus", "Kelleran Beq", "Ki-Adi-Mundi", "Kit Fisto", "Krrsantan",
        "Kyle Katarn", "Kylo Ren", "Kylo Ren (Unmasked)", "L3-37", "Leia Organa",
        "Lord Vader", "Luke Skywalker (Farmboy)", "Luthen Rael", "Mace Windu", "Mara Jade, The Emperor's Hand",
        "Marrok", "Master Qui-Gon", "Maul", "Merrin", "Mob Enforcer",
        "Moff Gideon", "Morgan Elsbeth", "Mother Talzin", "Night Trooper", "Nightsister Initiate",
        "Nightsister Spirit", "Nightsister Zombie", "Ninth Sister", "Old Daka", "Omega",
        "Omega (Fugitive)", "Padawan Obi-Wan", "Padawan Sabine Wren", "Paz Vizsla", "Princess Kneesaa",
        "Princess Leia", "Qi'ra", "Queen Amidala", "Qui-Gon Jinn", "RC-1262 \"Scorch\"",
        "Range Trooper", "Rebel Officer Leia Organa", "Resistance Hero Finn", "Rey", "Rey (Dark Side Vision)",
        "Rey (Jedi Training)", "Royal Guard", "SM-33", "Sabine Wren", "Sana Starros",
        "Savage Opress", "Saw Gerrera", "Second Sister", "Seventh Sister", "Shaak Ti",
        "Shin Hati", "Shoretrooper", "Sith Empire Trooper", "Sith Eternal Emperor", "Sith Marauder",
        "Skiff Guard (Lando Calrissian)", "Starkiller", "Sun Fac", "Supreme Leader Kylo Ren", "T3-M4",
        "Tarfful", "Taron Malicos", "The Armorer", "The Mandalorian", "The Mandalorian (Beskar Armor)",
        "Third Sister", "Threepio & Chewie", "Tusken Raider", "Tusken Warrior", "Vandor Chewbacca",
        "Veteran Smuggler Han Solo", "Visas Marr", "Wampa", "Wrecker (Mercenary)", "Young Han Solo",
        "Young Lando Calrissian", "Zaalbar", "Zam Wesell", "Zorii Bliss",
    ],
    "Critical Chance Down": [
        "Cal Kestis", "Chief Nebit", "Grand Moff Tarkin", "Leia Organa", "Night Trooper",
        "Padawan Obi-Wan", "Shin Hati", "Shoretrooper", "Sun Fac", "T3-M4",
    ],
    "Critical Chance Up": [
        "Admiral Raddus", "Aurra Sing", "BB-8", "Bastila Shan", "Biggs Darklighter",
        "Canderous Ordo", "Captain Rex", "Chewbacca", "Colonel Starck", "Darth Malgus",
        "Death Trooper (Peridea)", "Geonosian Spy", "Grand Master Yoda", "Greedo", "Greef Karga",
        "Han Solo", "Hunter", "Hunter (Mercenary)", "Jawa Engineer", "Jedi Knight Anakin",
        "Kyle Katarn", "Lando Calrissian", "Nightsister Initiate", "Omega", "Padawan Obi-Wan",
        "Princess Kneesaa", "Princess Leia", "Sabine Wren", "Sana Starros", "Savage Opress",
        "Shaak Ti", "Taron Malicos", "The Mandalorian", "Wicket",
    ],
    "Critical Damage Down": [
        "B2 Super Battle Droid", "Bastila Shan (Fallen)", "Dash Rendar", "Krrsantan", "Leia Organa",
        "Padawan Obi-Wan", "Paz Vizsla", "Saw Gerrera",
    ],
    "Critical Damage Up": [
        "Admiral Raddus", "BB-8", "Biggs Darklighter", "Boss Nass", "CC-1119 \"Appo\"",
        "CT-21-0408 \"Echo\"", "Cal Kestis", "Canderous Ordo", "Captain Enoch", "Captain Tarpals",
        "Colonel Starck", "Commander Ahsoka Tano", "Darth Malgus", "Darth Traya", "Dash Rendar",
        "Doctor Aphra", "General Syndulla", "Geonosian Brood Alpha", "Grand Inquisitor", "Grand Master Yoda",
        "Greef Karga", "Han Solo", "Iden Versio", "Jabba the Hutt", "Jedi Knight Revan",
        "Jedi Master Luke Skywalker", "Jocasta Nu", "Jyn Erso", "Luke Skywalker (Farmboy)", "Luthen Rael",
        "Master Qui-Gon", "Padawan Obi-Wan", "Princess Kneesaa", "Princess Leia", "Queen Amidala",
        "Rey (Jedi Training)", "Savage Opress", "Saw Gerrera", "Scout Trooper", "Second Sister",
        "Shin Hati", "Snowtrooper", "Supreme Leader Kylo Ren", "Tarfful", "Taron Malicos",
        "The Mandalorian", "Third Sister", "Tusken Warrior", "Wicket", "Young Han Solo",
        "Zorii Bliss",
    ],
    "Critical Hit Immunity": [
        "Ahsoka Tano (Snips)", "CT-7567 \"Rex\"", "Cal Kestis", "Cara Dune", "Count Dooku",
        "Eighth Brother", "General Kenobi", "Jedi Knight Revan", "Jedi Master Luke Skywalker", "Jyn Erso",
        "Ki-Adi-Mundi", "Mon Mothma", "Resistance Hero Finn", "Rey", "Saw Gerrera",
        "Seventh Sister", "Shaak Ti", "Shin Hati", "Shoretrooper", "Sith Trooper",
        "Starkiller", "T3-M4", "Taron Malicos", "The Armorer", "Zorii Bliss",
    ],
    "Damage Immunity": [
        "50R-T", "Ahsoka Tano", "Cere Junda", "Doctor Aphra", "Droideka",
        "Enfys Nest", "Fifth Brother", "Gamorrean Guard", "General Syndulla", "Great Mothers",
        "Huyang", "Imperial Super Commando", "Jabba the Hutt", "Jango Fett", "Jar Jar Binks",
        "Jedi Knight Cal Kestis", "Jedi Master Kenobi", "Jocasta Nu", "Krrsantan", "Leia Organa",
        "Marrok", "Paz Vizsla", "Queen Amidala", "Qui-Gon Jinn", "Rey",
        "Shin Hati", "Starkiller", "Taron Malicos", "The Mandalorian (Beskar Armor)", "Zorii Bliss",
    ],
    "Daze": [
        "Admiral Piett", "Admiral Raddus", "Ahsoka Tano", "Amilyn Holdo", "BB-8",
        "Baylan Skoll", "Bo-Katan (Mand'alor)", "Bo-Katan Kryze", "Boss Nass", "Cal Kestis",
        "Captain Han Solo", "Captain Rex", "Captain Tarpals", "Cere Junda", "Chewbacca",
        "Count Dooku", "Dark Trooper Moff Gideon", "Darth Bane", "Darth Maul", "Darth Traya",
        "Dash Rendar", "Death Trooper", "Death Trooper (Peridea)", "Droideka", "Echo",
        "Enfys Nest", "Garazeb \"Zeb\" Orrelios", "General Skywalker", "Grand Moff Tarkin", "Greef Karga",
        "Gungan Phalanx", "Hunter (Mercenary)", "IG-12 & Grogu", "Jabba the Hutt", "Jar Jar Binks",
        "Jedi Knight Cal Kestis", "Jedi Master Luke Skywalker", "Jocasta Nu", "K-2SO", "Ki-Adi-Mundi",
        "Leia Organa", "Logray", "Lord Vader", "Luthen Rael", "Mara Jade, The Emperor's Hand",
        "Mission Vao", "Mob Enforcer", "Moff Gideon", "Mon Mothma", "Ninth Sister",
        "Omega", "Padawan Obi-Wan", "Paz Vizsla", "Princess Kneesaa", "Qi'ra",
        "Resistance Hero Poe", "Rey (Jedi Training)", "Rey (Scavenger)", "Rose Tico", "SM-33",
        "Sana Starros", "Scout Trooper", "Seventh Sister", "Shin Hati", "Starkiller",
        "Sun Fac", "Taron Malicos", "Tech", "Veteran Smuggler Chewbacca", "Wampa",
        "Zaalbar",
    ],
    "Deathmark": [
        "Bastila Shan (Fallen)", "CC-1119 \"Appo\"", "Canderous Ordo", "Darth Revan", "Death Trooper",
        "HK-47", "Jar Jar Binks", "Third Sister",
    ],
    "Decay": [
        "Captain Enoch",
    ],
    "Defense Down": [
        "50R-T", "Amilyn Holdo", "Asajj Ventress", "Batcher", "Baylan Skoll",
        "Ben Solo", "Boss Nass", "Boushh (Leia Organa)", "C-3PO", "Cal Kestis",
        "Captain Phasma", "Cassian Andor", "Colonel Starck", "Commander Luke Skywalker", "Crosshair (Scarred)",
        "Dash Rendar", "Dathcha", "Eeth Koth", "Fifth Brother", "First Order SF TIE Pilot",
        "Grand Admiral Thrawn", "Grand Moff Tarkin", "Gungan Boomadier", "Gungan Phalanx", "IG-88",
        "Ima-Gun Di", "Jawa Scavenger", "Jocasta Nu", "L3-37", "Leia Organa",
        "Lobot", "Luke Skywalker (Farmboy)", "Luthen Rael", "Marrok", "Mob Enforcer",
        "Morgan Elsbeth", "Ninth Sister", "Padawan Obi-Wan", "Pao", "Saw Gerrera",
        "Shin Hati", "Sith Empire Trooper", "Taron Malicos", "Third Sister", "Tusken Warrior",
        "Ugnaught", "Wedge Antilles", "Wrecker (Mercenary)",
    ],
    "Defense Penetration Up": [
        "CC-1119 \"Appo\"", "Cere Junda", "Darth Bane", "Grand Inquisitor", "Grand Master Yoda",
        "Great Mothers", "Greef Karga", "Jabba the Hutt", "Jedi Knight Cal Kestis", "Jedi Master Kenobi",
        "Luthen Rael", "Mon Mothma", "Morgan Elsbeth", "Omega", "Padawan Obi-Wan",
        "Qi'ra", "Queen Amidala", "SM-33", "Tarfful", "Third Sister",
        "Visas Marr",
    ],
    "Defense Up": [
        "50R-T", "Admiral Piett", "Admiral Raddus", "Ahsoka Tano", "Barriss Offee",
        "Bo-Katan Kryze", "Cal Kestis", "Captain Tarpals", "Cassian Andor", "Cere Junda",
        "Clone Wars Chewbacca", "Dark Trooper Moff Gideon", "Darth Bane", "Ezra Bridger", "Ezra Bridger (Exile)",
        "Finn", "First Order Stormtrooper", "Gamorrean Guard", "General Syndulla", "Hondo Ohnaka",
        "Hoth Rebel Soldier", "Hunter", "IG-12 & Grogu", "Jedi Knight Guardian", "Jedi Master Luke Skywalker",
        "Kanan Jarrus", "Krrsantan", "Kyle Katarn", "Lobot", "Marrok",
        "Master Qui-Gon", "Morgan Elsbeth", "Obi-Wan Kenobi (Old Ben)", "Old Daka", "Omega",
        "Padawan Obi-Wan", "Paploo", "Plo Koon", "Queen Amidala", "Rose Tico",
        "Royal Guard", "SM-33", "Savage Opress", "Saw Gerrera", "Sith Empire Trooper",
        "Skiff Guard (Lando Calrissian)", "Sun Fac", "Tarfful", "Taron Malicos", "Wrecker",
        "Wrecker (Mercenary)", "Zaalbar",
    ],
    "Deflective Ward": [
        "Jocasta Nu", "RC-1262 \"Scorch\"",
    ],
    "Dispel": [
        "0-0-0", "50R-T", "ARC Trooper", "Admiral Ackbar", "Admiral Piett",
        "Admiral Raddus", "Admiral Trench", "Ahsoka Tano", "Ahsoka Tano (Fulcrum)", "Ahsoka Tano (Snips)",
        "Amilyn Holdo", "Asajj Ventress", "B1 Battle Droid", "B2 Super Battle Droid", "BB-8",
        "Barriss Offee", "Bastila Shan", "Bastila Shan (Fallen)", "Batcher", "Baylan Skoll",
        "Baze Malbus", "Ben Solo", "Bo-Katan (Mand'alor)", "Bo-Katan Kryze", "Boba Fett",
        "Boba Fett, Scion of Jango", "Boss Nass", "Bossk", "Boushh (Leia Organa)", "CC-1119 \"Appo\"",
        "CT-21-0408 \"Echo\"", "CT-7567 \"Rex\"", "CX-2", "Cad Bane", "Cal Kestis",
        "Captain Drogan", "Captain Enoch", "Captain Han Solo", "Captain Rex", "Captain Tarpals",
        "Cere Junda", "Chewbacca", "Chief Nebit", "Chirrut Îmwe", "Chopper",
        "Clone Wars Chewbacca", "Colonel Starck", "Commander Ahsoka Tano", "Commander Luke Skywalker", "Count Dooku",
        "Crosshair (Scarred)", "Dark Trooper", "Dark Trooper Moff Gideon", "Darth Bane", "Darth Malak",
        "Darth Malgus", "Darth Nihilus", "Darth Revan", "Darth Sion", "Darth Talon",
        "Darth Traya", "Darth Vader", "Dash Rendar", "Death Trooper", "Death Trooper (Peridea)",
        "Disguised Clone Trooper", "Droideka", "Echo", "Eighth Brother", "Embo",
        "Emperor Palpatine", "Enfys Nest", "Ewok Elder", "Ezra Bridger", "Ezra Bridger (Exile)",
        "Fennec Shand", "Fifth Brother", "Finn", "First Order Executioner", "First Order Officer",
        "First Order Stormtrooper", "Gamorrean Guard", "General Grievous", "General Hux", "General Kenobi",
        "General Skywalker", "General Syndulla", "Geonosian Brood Alpha", "Geonosian Spy", "Grand Admiral Thrawn",
        "Grand Inquisitor", "Grand Moff Tarkin", "Great Mothers", "Greedo", "Greef Karga",
        "Gungan Boomadier", "Gungan Phalanx", "HK-47", "Hera Syndulla", "Hermit Yoda",
        "Hondo Ohnaka", "Hunter (Mercenary)", "Huyang", "IG-100 MagnaGuard", "IG-11",
        "IG-12 & Grogu", "Iden Versio", "Imperial Probe Droid", "Imperial Super Commando", "Jabba the Hutt",
        "Jango Fett", "Jar Jar Binks", "Jedi Knight Anakin", "Jedi Knight Cal Kestis", "Jedi Knight Luke Skywalker",
        "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jocasta Nu", "Jolee Bindo",
        "Juhani", "K-2SO", "Kanan Jarrus", "Kelleran Beq", "Ki-Adi-Mundi",
        "Krrsantan", "Kyle Katarn", "Kylo Ren (Unmasked)", "L3-37", "Leia Organa",
        "Lobot", "Logray", "Lord Vader", "Luke Skywalker (Farmboy)", "Luminara Unduli",
        "Luthen Rael", "Mace Windu", "Mara Jade, The Emperor's Hand", "Marrok", "Master Qui-Gon",
        "Maul", "Merrin", "Mission Vao", "Moff Gideon", "Mon Mothma",
        "Morgan Elsbeth", "Mother Talzin", "Night Trooper", "Nightsister Acolyte", "Nightsister Spirit",
        "Nightsister Zombie", "Ninth Sister", "Nute Gunray", "Omega", "Omega (Fugitive)",
        "Padawan Obi-Wan", "Padawan Sabine Wren", "Padmé Amidala", "Paploo", "Paz Vizsla",
        "Plo Koon", "Poggle the Lesser", "Princess Kneesaa", "Qi'ra", "Queen Amidala",
        "Qui-Gon Jinn", "R2-D2", "RC-1262 \"Scorch\"", "Resistance Hero Finn", "Resistance Hero Poe",
        "Resistance Trooper", "Rey", "Rey (Dark Side Vision)", "Rey (Jedi Training)", "SM-33",
        "STAP", "Sana Starros", "Savage Opress", "Saw Gerrera", "Scout Trooper",
        "Second Sister", "Seventh Sister", "Shaak Ti", "Shin Hati", "Sith Assassin",
        "Sith Eternal Emperor", "Sith Trooper", "Skiff Guard (Lando Calrissian)", "Starkiller", "Sun Fac",
        "Supreme Leader Kylo Ren", "T3-M4", "Talia", "Tarfful", "Taron Malicos",
        "Tech", "Teebo", "The Armorer", "The Mandalorian (Beskar Armor)", "Third Sister",
        "Threepio & Chewie", "Tusken Chieftain", "Tusken Raider", "Tusken Warrior", "Veteran Smuggler Chewbacca",
        "Visas Marr", "Wampa", "Wat Tambor", "Wrecker", "Wrecker (Mercenary)",
        "Young Lando Calrissian", "Zaalbar", "Zam Wesell", "Zorii Bliss",
    ],
    "Dispel - All Enemies": [
        "B2 Super Battle Droid",
    ],
    "DoT": [
        "Ahsoka Tano (Fulcrum)", "B1 Battle Droid", "BT-1", "Bistan", "Boba Fett",
        "Boba Fett, Scion of Jango", "Boss Nass", "CC-1119 \"Appo\"", "CX-2", "Canderous Ordo",
        "Captain Rex", "Carth Onasi", "Darth Malak", "Darth Nihilus", "Darth Sidious",
        "Darth Vader", "Death Trooper (Peridea)", "Dengar", "Disguised Clone Trooper", "Doctor Aphra",
        "Gamorrean Guard", "General Syndulla", "Great Mothers", "IG-11", "IG-88",
        "Krrsantan", "Kylo Ren", "Lord Vader", "Luke Skywalker (Farmboy)", "Mission Vao",
        "Nightsister Initiate", "Ninth Sister", "Omega (Fugitive)", "Princess Kneesaa", "Queen Amidala",
        "RC-1262 \"Scorch\"", "Resistance Hero Poe", "SM-33", "Skiff Guard (Lando Calrissian)", "Talia",
        "Tarfful", "The Mandalorian (Beskar Armor)", "Tusken Chieftain", "Tusken Shaman", "Tusken Warrior",
        "Wampa", "Wat Tambor", "Zaalbar",
    ],
    "Doubt": [
        "Baylan Skoll", "Darth Malgus", "Doctor Aphra", "Master Qui-Gon", "Queen Amidala",
    ],
    "Evasion Down": [
        "Amilyn Holdo", "Bastila Shan (Fallen)", "Bodhi Rook", "Cal Kestis", "Geonosian Spy",
        "Krrsantan", "Obi-Wan Kenobi (Old Ben)", "Padawan Obi-Wan", "Sith Assassin", "Threepio & Chewie",
        "Zam Wesell",
    ],
    "Evasion Up": [
        "Biggs Darklighter", "Commander Ahsoka Tano", "Darth Bane", "Echo", "Han Solo",
        "Hunter", "Jyn Erso", "Luminara Unduli", "Omega", "Padawan Obi-Wan",
        "Seventh Sister",
    ],
    "Expose": [
        "Admiral Raddus", "BB-8", "BT-1", "Bastila Shan (Fallen)", "Baylan Skoll",
        "Boss Nass", "C-3PO", "CC-1119 \"Appo\"", "Cassian Andor", "Crosshair (Scarred)",
        "Darth Malgus", "Darth Sidious", "Doctor Aphra", "Echo", "Enfys Nest",
        "Fifth Brother", "Finn", "Gamorrean Guard", "Garazeb \"Zeb\" Orrelios", "Geonosian Brood Alpha",
        "Geonosian Spy", "Grand Moff Tarkin", "Gungan Phalanx", "Hera Syndulla", "Hondo Ohnaka",
        "Hunter", "Hunter (Mercenary)", "Huyang", "Imperial Probe Droid", "Jar Jar Binks",
        "Jedi Master Luke Skywalker", "Jocasta Nu", "Jyn Erso", "Kuiil", "Leia Organa",
        "Marrok", "Master Qui-Gon", "Mob Enforcer", "Morgan Elsbeth", "Omega",
        "Omega (Fugitive)", "Paz Vizsla", "Poe Dameron", "Qi'ra", "Queen Amidala",
        "Resistance Pilot", "Resistance Trooper", "Rey (Jedi Training)", "Rose Tico", "Sabine Wren",
        "Scout Trooper", "Sith Eternal Emperor", "Stormtrooper", "Wampa", "Zaalbar",
        "Zorii Bliss",
    ],
    "Fear": [
        "Admiral Piett", "Admiral Trench", "Bastila Shan (Fallen)", "Baylan Skoll", "Boushh (Leia Organa)",
        "Darth Malak", "Darth Malgus", "Darth Revan", "Darth Vader", "Fifth Brother",
        "Grand Moff Tarkin", "Great Mothers", "HK-47", "Jabba the Hutt", "Jar Jar Binks",
        "Jedi Knight Cal Kestis", "Jedi Knight Luke Skywalker", "Leia Organa", "Lord Vader", "Luthen Rael",
        "Padmé Amidala", "Queen Amidala", "Rey (Dark Side Vision)", "Shin Hati", "Starkiller",
    ],
    "Foresight": [
        "50R-T", "Admiral Trench", "Ahsoka Tano (Fulcrum)", "Ahsoka Tano (Snips)", "Amilyn Holdo",
        "BB-8", "Bastila Shan (Fallen)", "Baylan Skoll", "CC-1119 \"Appo\"", "Cal Kestis",
        "Cere Junda", "Darth Revan", "Eighth Brother", "Embo", "Enfys Nest",
        "Ezra Bridger (Exile)", "First Order TIE Pilot", "General Kenobi", "Grand Inquisitor", "Grand Master Yoda",
        "Great Mothers", "Gungan Phalanx", "Hermit Yoda", "Hondo Ohnaka", "IG-11",
        "Jar Jar Binks", "Jedi Knight Revan", "Jedi Master Kenobi", "Jocasta Nu", "Kanan Jarrus",
        "Kelleran Beq", "Leia Organa", "Lobot", "Logray", "Mace Windu",
        "Master Qui-Gon", "Morgan Elsbeth", "Nightsister Spirit", "Omega (Fugitive)", "Padawan Obi-Wan",
        "Princess Kneesaa", "Princess Leia", "Qui-Gon Jinn", "R2-D2", "Rebel Officer Leia Organa",
        "Resistance Pilot", "Rey (Jedi Training)", "Rey (Scavenger)", "Seventh Sister", "Shin Hati",
        "Sith Assassin", "TIE Fighter Pilot", "Tarfful", "Tech",
    ],
    "Frenzy": [
        "Bistan", "Bossk", "Darth Talon", "Gungan Boomadier", "Jedi Knight Cal Kestis",
        "Luthen Rael", "Maul", "Morgan Elsbeth", "Night Trooper", "Paz Vizsla",
    ],
    "Frustration": [
        "Jar Jar Binks",
    ],
    "Gain Turn Meter": [
        "0-0-0", "50R-T", "Admiral Ackbar", "Admiral Piett", "Admiral Raddus",
        "Admiral Trench", "Ahsoka Tano", "Ahsoka Tano (Fulcrum)", "Ahsoka Tano (Snips)", "Asajj Ventress",
        "Aurra Sing", "B1 Battle Droid", "B2 Super Battle Droid", "BB-8", "BT-1",
        "Barriss Offee", "Bastila Shan", "Bastila Shan (Fallen)", "Baylan Skoll", "Baze Malbus",
        "Ben Solo", "Biggs Darklighter", "Bistan", "Boba Fett", "Boba Fett, Scion of Jango",
        "Bodhi Rook", "Boss Nass", "Boushh (Leia Organa)", "C-3PO", "CC-1119 \"Appo\"",
        "CC-2224 \"Cody\"", "CT-5555 \"Fives\"", "CT-7567 \"Rex\"", "CX-2", "Cad Bane",
        "Cal Kestis", "Canderous Ordo", "Captain Drogan", "Captain Enoch", "Captain Han Solo",
        "Captain Phasma", "Captain Rex", "Captain Tarpals", "Cara Dune", "Carth Onasi",
        "Cassian Andor", "Cere Junda", "Chief Chirpa", "Chief Nebit", "Clone Sergeant - Phase I",
        "Clone Wars Chewbacca", "Colonel Starck", "Commander Ahsoka Tano", "Commander Luke Skywalker", "Coruscant Underworld Police",
        "Count Dooku", "Crosshair (Scarred)", "Dark Trooper", "Dark Trooper Moff Gideon", "Darth Bane",
        "Darth Malak", "Darth Malgus", "Darth Maul", "Darth Nihilus", "Darth Revan",
        "Darth Sidious", "Darth Sion", "Darth Talon", "Darth Vader", "Dash Rendar",
        "Death Trooper", "Death Trooper (Peridea)", "Dengar", "Disguised Clone Trooper", "Doctor Aphra",
        "Droideka", "Echo", "Eighth Brother", "Embo", "Emperor Palpatine",
        "Enfys Nest", "Ewok Elder", "Ewok Scout", "Ezra Bridger", "Fennec Shand",
        "Fifth Brother", "Finn", "First Order Executioner", "First Order Officer", "First Order Stormtrooper",
        "First Order TIE Pilot", "Garazeb \"Zeb\" Orrelios", "General Grievous", "General Hux", "General Kenobi",
        "General Skywalker", "General Syndulla", "General Veers", "Geonosian Brood Alpha", "Geonosian Soldier",
        "Geonosian Spy", "Grand Admiral Thrawn", "Grand Inquisitor", "Grand Master Yoda", "Grand Moff Tarkin",
        "Great Mothers", "Greedo", "Greef Karga", "Gungan Boomadier", "Gungan Phalanx",
        "HK-47", "Han Solo", "Hera Syndulla", "Hermit Yoda", "Hondo Ohnaka",
        "Hoth Rebel Scout", "Hunter", "Hunter (Mercenary)", "Huyang", "IG-12 & Grogu",
        "Iden Versio", "Imperial Probe Droid", "Imperial Super Commando", "Jabba the Hutt", "Jango Fett",
        "Jar Jar Binks", "Jawa", "Jawa Engineer", "Jedi Knight Cal Kestis", "Jedi Knight Luke Skywalker",
        "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jocasta Nu", "Jolee Bindo",
        "Juhani", "Jyn Erso", "Kanan Jarrus", "Kelleran Beq", "Ki-Adi-Mundi",
        "Kit Fisto", "Kuiil", "Kyle Katarn", "Kylo Ren", "Kylo Ren (Unmasked)",
        "L3-37", "Leia Organa", "Lobot", "Logray", "Lord Vader",
        "Luke Skywalker (Farmboy)", "Luminara Unduli", "Luthen Rael", "Mace Windu", "Magmatrooper",
        "Mara Jade, The Emperor's Hand", "Marrok", "Master Qui-Gon", "Merrin", "Mission Vao",
        "Moff Gideon", "Morgan Elsbeth", "Mother Talzin", "Night Trooper", "Nightsister Acolyte",
        "Nightsister Spirit", "Ninth Sister", "Obi-Wan Kenobi (Old Ben)", "Old Daka", "Omega",
        "Omega (Fugitive)", "Padawan Obi-Wan", "Padawan Sabine Wren", "Padmé Amidala", "Pao",
        "Paploo", "Paz Vizsla", "Plo Koon", "Poggle the Lesser", "Princess Kneesaa",
        "Princess Leia", "Qi'ra", "Queen Amidala", "Qui-Gon Jinn", "R2-D2",
        "RC-1262 \"Scorch\"", "Rebel Officer Leia Organa", "Resistance Hero Finn", "Resistance Pilot", "Resistance Trooper",
        "Rey", "Rey (Dark Side Vision)", "Rey (Jedi Training)", "Rose Tico", "SM-33",
        "STAP", "Sana Starros", "Savage Opress", "Saw Gerrera", "Scarif Rebel Pathfinder",
        "Scout Trooper", "Second Sister", "Seventh Sister", "Shaak Ti", "Shin Hati",
        "Shoretrooper", "Sith Assassin", "Sith Eternal Emperor", "Sith Marauder", "Snowtrooper",
        "Stormtrooper Han", "Supreme Leader Kylo Ren", "TIE Fighter Pilot", "Talia", "Tarfful",
        "Taron Malicos", "Teebo", "The Mandalorian", "The Mandalorian (Beskar Armor)", "Third Sister",
        "Tusken Chieftain", "Tusken Shaman", "URoRRuR'R'R", "Ugnaught", "Veteran Smuggler Chewbacca",
        "Veteran Smuggler Han Solo", "Wampa", "Wat Tambor", "Wicket", "Wrecker",
        "Wrecker (Mercenary)", "Young Lando Calrissian", "Zaalbar", "Zam Wesell", "Zorii Bliss",
    ],
    "Heal": [
        "Admiral Ackbar", "Admiral Raddus", "Ahsoka Tano (Snips)", "Barriss Offee", "Captain Rex",
        "Chief Chirpa", "Droideka", "Ewok Elder", "Ezra Bridger (Exile)", "Hermit Yoda",
        "Jawa Engineer", "Jedi Consular", "Jyn Erso", "Kuiil", "Lobot",
        "Luminara Unduli", "Mace Windu", "Old Daka", "Qui-Gon Jinn", "Seventh Sister",
        "Shoretrooper", "Starkiller", "T3-M4", "Tarfful", "Zorii Bliss",
    ],
    "Heal Over Time": [
        "Admiral Trench", "Chief Chirpa", "Chief Nebit", "Chirrut Îmwe", "Enfys Nest",
        "Luminara Unduli", "Master Qui-Gon", "Ninth Sister", "Padawan Obi-Wan", "Queen Amidala",
        "Royal Guard", "Savage Opress", "Saw Gerrera", "Wat Tambor",
    ],
    "Healing Immunity": [
        "Admiral Raddus", "Admiral Trench", "Asajj Ventress", "Barriss Offee", "Baylan Skoll",
        "Ben Solo", "Boba Fett", "Boss Nass", "Captain Enoch", "Cassian Andor",
        "Count Dooku", "Dark Trooper Moff Gideon", "Darth Bane", "Darth Malak", "Darth Malgus",
        "Darth Sidious", "Darth Traya", "Death Trooper", "Disguised Clone Trooper", "Doctor Aphra",
        "Echo", "Eighth Brother", "Ezra Bridger (Exile)", "General Grievous", "General Syndulla",
        "Gungan Boomadier", "Hermit Yoda", "Hunter (Mercenary)", "IG-12 & Grogu", "IG-88",
        "Iden Versio", "Jango Fett", "Jawa Scavenger", "Jedi Knight Anakin", "Jedi Master Kenobi",
        "Kelleran Beq", "Kylo Ren", "Lord Vader", "Luthen Rael", "Master Qui-Gon",
        "Night Trooper", "Padawan Obi-Wan", "Paz Vizsla", "Queen Amidala", "Rey (Jedi Training)",
        "SM-33", "Sana Starros", "Seventh Sister", "Starkiller", "Taron Malicos",
        "The Mandalorian (Beskar Armor)", "Third Sister", "Wampa", "Wrecker (Mercenary)", "Zorii Bliss",
    ],
    "Health Steal Up": [
        "50R-T", "Baylan Skoll", "Cal Kestis", "Darth Bane", "Darth Traya",
        "Emperor Palpatine", "Ezra Bridger (Exile)", "General Grievous", "Greef Karga", "IG-11",
        "Juhani", "Qi'ra", "Shin Hati", "Sun Fac", "Visas Marr",
    ],
    "Health Up": [
        "Admiral Raddus", "Clone Wars Chewbacca", "Darth Bane", "First Order Executioner", "Hoth Rebel Soldier",
        "Logray", "Royal Guard", "Skiff Guard (Lando Calrissian)", "Sun Fac", "Tarfful",
    ],
    "Inspired": [
        "Resistance Hero Finn", "Resistance Hero Poe", "Rey",
    ],
    "Instant Defeat": [
        "Baylan Skoll", "Commander Ahsoka Tano", "Darth Nihilus", "Death Trooper (Peridea)", "Grand Inquisitor",
        "Imperial Probe Droid", "Jar Jar Binks", "Jedi Knight Cal Kestis", "Omega (Fugitive)", "SM-33",
        "The Mandalorian", "Zaalbar",
    ],
    "Instant Defeat Immunity": [
        "50R-T", "Ben Solo", "CX-2", "Ezra Bridger (Exile)", "Great Mothers",
        "Merrin",
    ],
    "Leader: +Critical": [
        "50R-T", "Admiral Raddus", "Boba Fett", "CC-2224 \"Cody\"", "Cere Junda",
        "Chief Nebit", "Dark Trooper Moff Gideon", "Darth Malgus", "Darth Revan", "Darth Sidious",
        "Director Krennic", "Grand Master Yoda", "Greef Karga", "HK-47", "IG-88",
        "Iden Versio", "Jango Fett", "Jedi Knight Luke Skywalker", "Kelleran Beq", "Lord Vader",
        "Princess Leia", "Qi'ra", "Rebel Officer Leia Organa", "Rey (Jedi Training)", "The Mandalorian",
    ],
    "Leader: +Defense": [
        "50R-T", "Admiral Piett", "Admiral Raddus", "Admiral Trench", "Ahsoka Tano",
        "Baylan Skoll", "Bo-Katan (Mand'alor)", "Bo-Katan Kryze", "Bossk", "CC-2224 \"Cody\"",
        "CT-5555 \"Fives\"", "Carth Onasi", "Cere Junda", "Clone Wars Chewbacca", "Commander Luke Skywalker",
        "Dark Trooper Moff Gideon", "Darth Bane", "Dathcha", "Eeth Koth", "Fennec Shand",
        "Fifth Brother", "Finn", "Gar Saxon", "General Grievous", "General Kenobi",
        "General Syndulla", "Grand Inquisitor", "Grand Moff Tarkin", "Great Mothers", "Hunter",
        "Ima-Gun Di", "Jabba the Hutt", "Jedi Knight Cal Kestis", "Jedi Master Luke Skywalker", "Kelleran Beq",
        "Kit Fisto", "Leia Organa", "Maul", "Mon Mothma", "Ninth Sister",
        "Old Daka", "Queen Amidala", "Sana Starros", "Savage Opress", "Saw Gerrera",
        "Sith Eternal Emperor", "Stormtrooper Han", "Tarfful", "Third Sister", "Tusken Chieftain",
        "URoRRuR'R'R",
    ],
    "Leader: +Evasion": [
        "Ahsoka Tano (Snips)", "Baylan Skoll", "Darth Bane", "Darth Maul", "Emperor Palpatine",
        "Hunter", "Luminara Unduli", "Obi-Wan Kenobi (Old Ben)", "Seventh Sister", "Talia",
    ],
    "Leader: +Max Health": [
        "50R-T", "Aayla Secura", "Admiral Trench", "Ahsoka Tano", "Barriss Offee",
        "Bo-Katan (Mand'alor)", "Boba Fett", "Boba Fett, Scion of Jango", "Boushh (Leia Organa)", "CT-7567 \"Rex\"",
        "Captain Enoch", "Carth Onasi", "Cere Junda", "Darth Bane", "Darth Malgus",
        "Darth Nihilus", "Darth Traya", "Dash Rendar", "Doctor Aphra", "Eighth Brother",
        "Emperor Palpatine", "Fennec Shand", "Fifth Brother", "Finn", "General Kenobi",
        "General Syndulla", "Geonosian Brood Alpha", "Grand Inquisitor", "Grand Moff Tarkin", "Great Mothers",
        "Hera Syndulla", "Hunter", "Iden Versio", "Jabba the Hutt", "Jedi Knight Cal Kestis",
        "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Krrsantan", "Leia Organa",
        "Lord Vader", "Luminara Unduli", "Mace Windu", "Maul", "Moff Gideon",
        "Mon Mothma", "Omega (Fugitive)", "Padmé Amidala", "Queen Amidala", "Rey",
        "Sana Starros", "Saw Gerrera", "Shaak Ti", "Talia", "Tarfful",
        "The Mandalorian (Beskar Armor)", "Third Sister", "Wedge Antilles",
    ],
    "Leader: +Speed": [
        "50R-T", "Admiral Ackbar", "Admiral Piett", "Admiral Raddus", "Admiral Trench",
        "Asajj Ventress", "Bo-Katan (Mand'alor)", "Boba Fett", "Boba Fett, Scion of Jango", "Boss Nass",
        "Bossk", "Captain Enoch", "Captain Phasma", "Chief Chirpa", "Dark Trooper Moff Gideon",
        "Darth Bane", "Darth Malgus", "Darth Revan", "Dash Rendar", "Doctor Aphra",
        "Fifth Brother", "Finn", "General Skywalker", "General Syndulla", "General Veers",
        "Grand Inquisitor", "Grand Moff Tarkin", "Great Mothers", "Hera Syndulla", "Iden Versio",
        "Jabba the Hutt", "Jango Fett", "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Kenobi",
        "Jedi Master Luke Skywalker", "Kelleran Beq", "Kylo Ren (Unmasked)", "Lando Calrissian", "Leia Organa",
        "Lobot", "Lord Vader", "Mother Talzin", "Ninth Sister", "Nute Gunray",
        "Qi'ra", "Queen Amidala", "Qui-Gon Jinn", "Rebel Officer Leia Organa", "Rey",
        "Saw Gerrera", "Shaak Ti", "Sith Eternal Emperor", "Supreme Leader Kylo Ren", "The Mandalorian",
        "Third Sister",
    ],
    "Leader: +Tenacity": [
        "Aayla Secura", "Admiral Ackbar", "Admiral Piett", "Admiral Raddus", "Bastila Shan",
        "Baylan Skoll", "Bo-Katan Kryze", "Boba Fett", "Boba Fett, Scion of Jango", "Bossk",
        "Boushh (Leia Organa)", "Cad Bane", "Captain Enoch", "Carth Onasi", "Cere Junda",
        "Count Dooku", "Darth Malgus", "Doctor Aphra", "Grand Master Yoda", "Jango Fett",
        "Jedi Knight Revan", "Jedi Master Luke Skywalker", "Kelleran Beq", "Kit Fisto", "Luke Skywalker (Farmboy)",
        "Mon Mothma", "Ninth Sister", "Rebel Officer Leia Organa", "Sana Starros", "Savage Opress",
        "Saw Gerrera", "Tarfful", "The Mandalorian", "Tusken Chieftain",
    ],
    "Leader: Assist": [
        "Admiral Ackbar", "Admiral Trench", "Baylan Skoll", "Bo-Katan Kryze", "Captain Phasma",
        "Carth Onasi", "Chief Chirpa", "General Kenobi", "Grand Moff Tarkin", "Great Mothers",
        "Jedi Knight Luke Skywalker", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Kelleran Beq",
        "Maul", "Mon Mothma", "Mother Talzin", "Queen Amidala", "Saw Gerrera",
    ],
    "Leader: Foresight": [
        "50R-T", "Baylan Skoll", "Cere Junda", "Eighth Brother", "Grand Inquisitor",
        "Kelleran Beq", "Leia Organa", "Qui-Gon Jinn", "Rebel Officer Leia Organa", "Seventh Sister",
        "Tarfful",
    ],
    "Leader: Healing": [
        "Barriss Offee", "Leia Organa", "Luminara Unduli", "Second Sister",
    ],
    "Leader: Health Up": [
        "Admiral Raddus", "Darth Bane",
    ],
    "Leader: Protection Up": [
        "50R-T", "Admiral Raddus", "Ahsoka Tano", "Bastila Shan", "Baylan Skoll",
        "Cere Junda", "Finn", "Grand Moff Tarkin", "Jedi Master Kenobi", "Leia Organa",
        "Padmé Amidala", "Queen Amidala", "Sana Starros", "Tarfful", "The Armorer",
        "Third Sister",
    ],
    "Marked": [
        "Admiral Piett", "Bastila Shan (Fallen)", "Batcher", "Canderous Ordo", "Captain Tarpals",
        "Crosshair (Scarred)", "Droideka", "General Grievous", "Hunter (Mercenary)", "Jedi Knight Revan",
        "Lord Vader", "Luthen Rael", "Saw Gerrera", "Second Sister",
    ],
    "Momentum": [
        "Boba Fett, Scion of Jango", "Tusken Chieftain", "Tusken Warrior",
    ],
    "Off Balance": [
        "Ahsoka Tano", "Batcher", "General Syndulla", "Huyang", "Padawan Sabine Wren",
        "RC-1262 \"Scorch\"",
    ],
    "Offense Down": [
        "Bastila Shan (Fallen)", "Batcher", "Baylan Skoll", "Ben Solo", "Boss Nass",
        "C-3PO", "Canderous Ordo", "Captain Drogan", "Captain Rex", "Cassian Andor",
        "Coruscant Underworld Police", "Dark Trooper Moff Gideon", "Death Trooper (Peridea)", "Disguised Clone Trooper", "Ezra Bridger (Exile)",
        "First Order TIE Pilot", "Grand Moff Tarkin", "Gungan Boomadier", "Hoth Rebel Soldier", "Hunter (Mercenary)",
        "Imperial Super Commando", "Jawa Scavenger", "Jedi Knight Guardian", "K-2SO", "Kanan Jarrus",
        "Krrsantan", "Mara Jade, The Emperor's Hand", "Maul", "Obi-Wan Kenobi (Old Ben)", "Padawan Obi-Wan",
        "Plo Koon", "Poe Dameron", "Qi'ra", "Rey (Jedi Training)", "Savage Opress",
        "Scarif Rebel Pathfinder", "Seventh Sister", "Shin Hati", "Sith Empire Trooper", "Sith Marauder",
        "Sun Fac", "T3-M4",
    ],
    "Offense Up": [
        "0-0-0", "50R-T", "Admiral Piett", "Admiral Raddus", "Aurra Sing",
        "BB-8", "Baylan Skoll", "Ben Solo", "Bodhi Rook", "Bossk",
        "CX-2", "Captain Rex", "Captain Tarpals", "Carth Onasi", "Chewbacca",
        "Chopper", "Clone Sergeant - Phase I", "Dark Trooper", "Darth Bane", "Darth Maul",
        "Darth Vader", "Dash Rendar", "Death Trooper (Peridea)", "Doctor Aphra", "Embo",
        "Emperor Palpatine", "Fennec Shand", "First Order Officer", "General Kenobi", "General Veers",
        "Geonosian Brood Alpha", "Grand Inquisitor", "Grand Master Yoda", "Greef Karga", "Gungan Phalanx",
        "HK-47", "Hunter", "Hunter (Mercenary)", "Huyang", "IG-12 & Grogu",
        "Jabba the Hutt", "Jawa Scavenger", "Jedi Knight Anakin", "Juhani", "Jyn Erso",
        "Kelleran Beq", "Logray", "Luke Skywalker (Farmboy)", "Mob Enforcer", "Obi-Wan Kenobi (Old Ben)",
        "Old Daka", "Padawan Obi-Wan", "Pao", "Plo Koon", "Poggle the Lesser",
        "Princess Kneesaa", "Princess Leia", "Queen Amidala", "Qui-Gon Jinn", "Rey (Jedi Training)",
        "Rey (Scavenger)", "Sabine Wren", "Savage Opress", "Saw Gerrera", "Scarif Rebel Pathfinder",
        "Scout Trooper", "Seventh Sister", "Shaak Ti", "Shin Hati", "Sith Assassin",
        "T3-M4", "Taron Malicos", "Tusken Shaman", "URoRRuR'R'R",
    ],
    "Perfect Defense": [
        "Ahsoka Tano", "General Syndulla",
    ],
    "Plague": [
        "Leia Organa", "Merrin", "Mother Talzin", "Omega (Fugitive)",
    ],
    "Plasma Residue": [
        "Jar Jar Binks",
    ],
    "Potency Down": [
        "Ben Solo", "Boba Fett, Scion of Jango", "Grand Master Yoda", "Krrsantan", "Leia Organa",
        "Ninth Sister", "Padawan Obi-Wan", "Princess Kneesaa", "Queen Amidala", "Young Lando Calrissian",
    ],
    "Potency Up": [
        "Admiral Raddus", "Baylan Skoll", "Bodhi Rook", "C-3PO", "CT-7567 \"Rex\"",
        "Cara Dune", "Cassian Andor", "Doctor Aphra", "Eighth Brother", "Fifth Brother",
        "Geonosian Spy", "Grand Moff Tarkin", "Greedo", "Gungan Phalanx", "Kit Fisto",
        "Kyle Katarn", "Obi-Wan Kenobi (Old Ben)", "Padawan Obi-Wan", "Scout Trooper", "Sith Marauder",
        "Skiff Guard (Lando Calrissian)", "Tarfful", "Tech", "Young Lando Calrissian",
    ],
    "Prepared": [
        "Dash Rendar", "L3-37", "Qi'ra", "Vandor Chewbacca", "Young Han Solo",
        "Young Lando Calrissian",
    ],
    "Protection Disruption": [
        "Admiral Raddus", "Boba Fett, Scion of Jango", "Gungan Boomadier", "Gungan Phalanx", "Hunter (Mercenary)",
        "Jar Jar Binks", "Jocasta Nu", "Master Qui-Gon",
    ],
    "Protection Over Time": [
        "Admiral Trench", "Boss Nass", "CT-5555 \"Fives\"", "Gungan Phalanx", "Master Qui-Gon",
        "Omega", "Padawan Obi-Wan", "Queen Amidala", "Wat Tambor",
    ],
    "Protection Up": [
        "50R-T", "Admiral Raddus", "Admiral Trench", "Ahsoka Tano", "Ahsoka Tano (Fulcrum)",
        "Ahsoka Tano (Snips)", "Bastila Shan", "Baylan Skoll", "Boba Fett, Scion of Jango", "C-3PO",
        "Cal Kestis", "Captain Drogan", "Captain Enoch", "Cassian Andor", "Cere Junda",
        "Chief Nebit", "Chopper", "Darth Malgus", "Darth Traya", "Doctor Aphra",
        "Ezra Bridger", "Ezra Bridger (Exile)", "Fifth Brother", "Finn", "Gamorrean Guard",
        "Garazeb \"Zeb\" Orrelios", "General Kenobi", "General Syndulla", "Grand Inquisitor", "Grand Master Yoda",
        "Grand Moff Tarkin", "HK-47", "Hondo Ohnaka", "Hunter (Mercenary)", "IG-12 & Grogu",
        "Iden Versio", "Jabba the Hutt", "Jar Jar Binks", "Jedi Knight Anakin", "Jedi Knight Cal Kestis",
        "Jedi Master Kenobi", "Jolee Bindo", "Kanan Jarrus", "Kelleran Beq", "Ki-Adi-Mundi",
        "Krrsantan", "Leia Organa", "Luminara Unduli", "Master Qui-Gon", "Mission Vao",
        "Moff Gideon", "Morgan Elsbeth", "Omega", "Padmé Amidala", "Paz Vizsla",
        "Princess Kneesaa", "Queen Amidala", "RC-1262 \"Scorch\"", "Range Trooper", "Rey (Dark Side Vision)",
        "Sana Starros", "Shin Hati", "Sith Empire Trooper", "Stormtrooper", "Tarfful",
        "Taron Malicos", "The Armorer", "Third Sister", "Tusken Chieftain", "Vandor Chewbacca",
        "Wampa", "Young Han Solo", "Zorii Bliss",
    ],
    "Provoked": [
        "Fifth Brother", "Gungan Phalanx", "STAP", "Tarfful",
    ],
    "Purge": [
        "Baylan Skoll", "Eighth Brother", "Fifth Brother", "Grand Inquisitor", "Marrok",
        "Ninth Sister", "Second Sister", "Seventh Sister", "Shin Hati", "Third Sister",
    ],
    "Reduce Cooldowns": [
        "0-0-0", "Admiral Raddus", "B2 Super Battle Droid", "Bastila Shan (Fallen)", "Baylan Skoll",
        "Boba Fett", "Bossk", "C-3PO", "CT-7567 \"Rex\"", "Cad Bane",
        "Chopper", "Darth Bane", "Darth Malgus", "Darth Nihilus", "Darth Revan",
        "Darth Traya", "Doctor Aphra", "Echo", "Gar Saxon", "General Skywalker",
        "Hera Syndulla", "Huyang", "IG-12 & Grogu", "Jedi Consular", "Jedi Knight Revan",
        "Jedi Master Luke Skywalker", "Krrsantan", "Lord Vader", "Maul", "Nute Gunray",
        "Omega (Fugitive)", "Pao", "Rey (Jedi Training)", "Sabine Wren", "Sana Starros",
        "Saw Gerrera", "Starkiller", "Taron Malicos", "Tech", "Tusken Chieftain",
    ],
    "Remove Turn Meter": [
        "50R-T", "Admiral Trench", "Ahsoka Tano", "Asajj Ventress", "Barriss Offee",
        "Ben Solo", "Bistan", "Bodhi Rook", "Boss Nass", "CC-1119 \"Appo\"",
        "CT-7567 \"Rex\"", "Cad Bane", "Captain Drogan", "Captain Enoch", "Captain Tarpals",
        "Cara Dune", "Clone Sergeant - Phase I", "Clone Wars Chewbacca", "Colonel Starck", "Commander Luke Skywalker",
        "Crosshair (Scarred)", "Dark Trooper Moff Gideon", "Darth Bane", "Darth Vader", "Dathcha",
        "Death Trooper (Peridea)", "Disguised Clone Trooper", "Enfys Nest", "Ewok Scout", "Fifth Brother",
        "First Order Executioner", "First Order Officer", "Gamorrean Guard", "General Grievous", "General Skywalker",
        "General Syndulla", "Geonosian Brood Alpha", "Grand Admiral Thrawn", "Grand Inquisitor", "Grand Master Yoda",
        "Grand Moff Tarkin", "Great Mothers", "Greedo", "Gungan Boomadier", "Gungan Phalanx",
        "Han Solo", "Hondo Ohnaka", "Hunter", "Imperial Probe Droid", "Jar Jar Binks",
        "Jedi Master Luke Skywalker", "Jyn Erso", "Leia Organa", "Lobot", "Logray",
        "Mace Windu", "Magmatrooper", "Master Qui-Gon", "Night Trooper", "Nightsister Spirit",
        "Obi-Wan Kenobi (Old Ben)", "Omega", "Omega (Fugitive)", "Padawan Obi-Wan", "Padawan Sabine Wren",
        "Paz Vizsla", "Poe Dameron", "Poggle the Lesser", "Princess Kneesaa", "Queen Amidala",
        "Qui-Gon Jinn", "Rey (Dark Side Vision)", "Rey (Jedi Training)", "Rose Tico", "SM-33",
        "Sana Starros", "Saw Gerrera", "Scout Trooper", "Second Sister", "Seventh Sister",
        "Shin Hati", "Stormtrooper", "Stormtrooper Han", "Sun Fac", "T3-M4",
        "Teebo", "The Mandalorian (Beskar Armor)", "Tusken Chieftain", "Tusken Raider", "Wat Tambor",
        "Wrecker (Mercenary)", "Zorii Bliss",
    ],
    "Reset Cooldown": [
        "Asajj Ventress", "Aurra Sing", "Boushh (Leia Organa)", "C-3PO", "Cal Kestis",
        "Captain Rex", "Captain Tarpals", "Carth Onasi", "Chewbacca", "Darth Bane",
        "Darth Malak", "Darth Traya", "Death Trooper (Peridea)", "Enfys Nest", "Ezra Bridger",
        "First Order Executioner", "General Grievous", "General Hux", "General Skywalker", "Grand Inquisitor",
        "Great Mothers", "HK-47", "Hermit Yoda", "Hunter (Mercenary)", "Huyang",
        "IG-100 MagnaGuard", "IG-12 & Grogu", "Jabba the Hutt", "Jar Jar Binks", "Jedi Master Kenobi",
        "Jedi Master Luke Skywalker", "Ki-Adi-Mundi", "Krrsantan", "Kyle Katarn", "Kylo Ren",
        "Lando Calrissian", "Luthen Rael", "Marrok", "Paz Vizsla", "Rey (Dark Side Vision)",
        "SM-33", "Sith Trooper", "Starkiller", "Taron Malicos", "Tech",
        "The Mandalorian (Beskar Armor)", "Tusken Warrior", "Veteran Smuggler Chewbacca", "Veteran Smuggler Han Solo", "Wrecker (Mercenary)",
    ],
    "Retaliate": [
        "Gungan Phalanx", "Rey (Dark Side Vision)",
    ],
    "Retribution": [
        "Ahsoka Tano (Fulcrum)", "Bastila Shan", "Baylan Skoll", "Baze Malbus", "Boss Nass",
        "Chief Chirpa", "Dark Trooper Moff Gideon", "Darth Talon", "Disguised Clone Trooper", "Fifth Brother",
        "Finn", "Gamorrean Guard", "Garazeb \"Zeb\" Orrelios", "General Kenobi", "Greef Karga",
        "Gungan Boomadier", "IG-11", "Jedi Knight Cal Kestis", "Kylo Ren", "Leia Organa",
        "Luthen Rael", "Maul", "Omega (Fugitive)", "Paz Vizsla", "Princess Kneesaa",
        "Princess Leia", "Range Trooper", "Rey (Dark Side Vision)", "Royal Guard", "Shaak Ti",
        "Shin Hati", "Sith Empire Trooper", "Sith Eternal Emperor", "Skiff Guard (Lando Calrissian)", "Tarfful",
        "Young Han Solo", "Zaalbar", "Zorii Bliss",
    ],
    "Revive": [
        "50R-T", "ARC Trooper", "Admiral Raddus", "Ahsoka Tano (Fulcrum)", "B1 Battle Droid",
        "Baylan Skoll", "Ben Solo", "Bo-Katan (Mand'alor)", "Boba Fett", "Boss Nass",
        "Boushh (Leia Organa)", "CC-1119 \"Appo\"", "CT-5555 \"Fives\"", "Captain Han Solo", "Cara Dune",
        "Dark Trooper", "Dark Trooper Moff Gideon", "Darth Bane", "Darth Nihilus", "Darth Sion",
        "Death Trooper", "Director Krennic", "Doctor Aphra", "Droideka", "Ewok Elder",
        "Finn", "General Skywalker", "Geonosian Brood Alpha", "Grand Inquisitor", "Grand Moff Tarkin",
        "Great Mothers", "Gungan Boomadier", "Hera Syndulla", "Iden Versio", "Imperial Probe Droid",
        "Jabba the Hutt", "Jango Fett", "Jawa Engineer", "Jedi Knight Cal Kestis", "Jocasta Nu",
        "Jolee Bindo", "Jyn Erso", "Krrsantan", "Kuiil", "Leia Organa",
        "Luthen Rael", "Marrok", "Merrin", "Moff Gideon", "Mon Mothma",
        "Morgan Elsbeth", "Mother Talzin", "Nightsister Zombie", "Nute Gunray", "Old Daka",
        "Omega (Fugitive)", "Paz Vizsla", "Poggle the Lesser", "Queen Amidala", "Qui-Gon Jinn",
        "R2-D2", "Rey", "Rey (Dark Side Vision)", "SM-33", "Saw Gerrera",
        "Scarif Rebel Pathfinder", "Shin Hati", "Sith Eternal Emperor", "Supreme Leader Kylo Ren", "Taron Malicos",
        "The Mandalorian", "The Mandalorian (Beskar Armor)", "Third Sister", "Threepio & Chewie", "Tusken Raider",
        "Vandor Chewbacca", "Visas Marr", "Wat Tambor", "Wrecker (Mercenary)", "Zaalbar",
    ],
    "Riposte": [
        "Count Dooku", "Ezra Bridger (Exile)", "Jedi Knight Cal Kestis", "Omega (Fugitive)", "Shin Hati",
        "Taron Malicos",
    ],
    "Shield Up": [
        "Gungan Phalanx", "Jar Jar Binks", "Rey (Dark Side Vision)",
    ],
    "Shock": [
        "0-0-0", "Admiral Trench", "Bastila Shan (Fallen)", "Captain Tarpals", "Count Dooku",
        "Darth Malak", "Darth Malgus", "Darth Revan", "Death Trooper (Peridea)", "Emperor Palpatine",
        "Grand Master Yoda", "Gungan Boomadier", "Hunter (Mercenary)", "IG-11", "Jar Jar Binks",
        "Krrsantan", "Kuiil", "Mara Jade, The Emperor's Hand", "Rey (Dark Side Vision)", "Starkiller",
    ],
    "Soldier of Fortune": [
        "Baylan Skoll", "Hunter (Mercenary)", "Marrok", "Shin Hati", "Wrecker (Mercenary)",
    ],
    "Speed Down": [
        "50R-T", "Bastila Shan (Fallen)", "Baze Malbus", "Ben Solo", "Boss Nass",
        "CT-5555 \"Fives\"", "CX-2", "Cal Kestis", "Captain Phasma", "Cassian Andor",
        "Commander Luke Skywalker", "Darth Vader", "Death Trooper (Peridea)", "Dengar", "Director Krennic",
        "Doctor Aphra", "Eighth Brother", "Ezra Bridger (Exile)", "First Order Stormtrooper", "Gar Saxon",
        "Grand Admiral Thrawn", "Great Mothers", "Gungan Boomadier", "Hunter (Mercenary)", "Jabba the Hutt",
        "Jawa", "Jedi Knight Cal Kestis", "Kuiil", "Lobot", "Luke Skywalker (Farmboy)",
        "Mace Windu", "Night Trooper", "Nightsister Spirit", "Nute Gunray", "Padawan Obi-Wan",
        "Paploo", "Princess Kneesaa", "Queen Amidala", "RC-1262 \"Scorch\"", "Resistance Trooper",
        "Rey (Jedi Training)", "Royal Guard", "STAP", "Scout Trooper", "Seventh Sister",
        "Veteran Smuggler Chewbacca", "Wrecker", "Wrecker (Mercenary)", "Young Han Solo", "Zorii Bliss",
    ],
    "Speed Up": [
        "50R-T", "BB-8", "Batcher", "Baylan Skoll", "Bo-Katan (Mand'alor)",
        "Boss Nass", "CX-2", "Cal Kestis", "Chief Chirpa", "Chopper",
        "Darth Bane", "Death Trooper (Peridea)", "First Order SF TIE Pilot", "General Syndulla", "General Veers",
        "Grand Admiral Thrawn", "Grand Inquisitor", "Gungan Boomadier", "Hunter (Mercenary)", "Huyang",
        "IG-100 MagnaGuard", "Jabba the Hutt", "Jocasta Nu", "Jyn Erso", "Krrsantan",
        "Kyle Katarn", "Lobot", "Lord Vader", "Luthen Rael", "Master Qui-Gon",
        "Obi-Wan Kenobi (Old Ben)", "Omega (Fugitive)", "Padawan Obi-Wan", "Queen Amidala", "Rey (Dark Side Vision)",
        "Saw Gerrera", "Scarif Rebel Pathfinder", "Scout Trooper", "Shaak Ti", "Sith Assassin",
        "Sith Eternal Emperor", "Skiff Guard (Lando Calrissian)", "Tarfful", "URoRRuR'R'R", "Young Lando Calrissian",
        "Zam Wesell", "Zorii Bliss",
    ],
    "Stagger": [
        "Admiral Trench", "Bastila Shan (Fallen)", "Baylan Skoll", "Captain Tarpals", "Colonel Starck",
        "Dark Trooper Moff Gideon", "Director Krennic", "Doctor Aphra", "Ezra Bridger (Exile)", "Garazeb \"Zeb\" Orrelios",
        "Huyang", "Jango Fett", "Jar Jar Binks", "Jedi Knight Cal Kestis", "Juhani",
        "Leia Organa", "Mara Jade, The Emperor's Hand", "Morgan Elsbeth", "Padawan Obi-Wan", "Paz Vizsla",
        "Qi'ra", "Queen Amidala", "RC-1262 \"Scorch\"", "Resistance Hero Poe", "SM-33",
        "Sabine Wren", "Sana Starros", "Saw Gerrera", "Scout Trooper", "Sun Fac",
        "Supreme Leader Kylo Ren", "Talia", "Veteran Smuggler Han Solo", "Wampa", "Wrecker (Mercenary)",
    ],
    "Stealth": [
        "50R-T", "Admiral Piett", "Admiral Trench", "Aurra Sing", "Batcher",
        "C-3PO", "CC-1119 \"Appo\"", "CX-2", "Cara Dune", "Chief Nebit",
        "Count Dooku", "Dark Trooper Moff Gideon", "Darth Maul", "Darth Talon", "Darth Vader",
        "Dash Rendar", "Dathcha", "Dengar", "Disguised Clone Trooper", "Eighth Brother",
        "Enfys Nest", "General Kenobi", "Geonosian Spy", "Grand Master Yoda", "Grand Moff Tarkin",
        "Great Mothers", "Greef Karga", "Hermit Yoda", "Hunter", "IG-100 MagnaGuard",
        "Jabba the Hutt", "Jar Jar Binks", "Jawa Scavenger", "Jedi Master Kenobi", "Juhani",
        "Leia Organa", "Lord Vader", "Luthen Rael", "Mace Windu", "Mara Jade, The Emperor's Hand",
        "Master Qui-Gon", "Merrin", "Mission Vao", "Morgan Elsbeth", "Nightsister Acolyte",
        "Nute Gunray", "Omega", "Omega (Fugitive)", "Paploo", "Plo Koon",
        "Princess Leia", "Queen Amidala", "Qui-Gon Jinn", "R2-D2", "Rey (Dark Side Vision)",
        "Sana Starros", "Saw Gerrera", "Scout Trooper", "Second Sister", "Shaak Ti",
        "Shin Hati", "Sith Assassin", "Skiff Guard (Lando Calrissian)", "T3-M4", "Tech",
        "Teebo", "The Mandalorian (Beskar Armor)", "Wicket", "Wrecker", "Wrecker (Mercenary)",
        "Young Lando Calrissian", "Zaalbar", "Zam Wesell", "Zorii Bliss",
    ],
    "Stun": [
        "0-0-0", "Aayla Secura", "Admiral Trench", "Ahsoka Tano", "Asajj Ventress",
        "Aurra Sing", "Bastila Shan", "Baylan Skoll", "Bo-Katan (Mand'alor)", "Boba Fett, Scion of Jango",
        "Boss Nass", "Bossk", "Boushh (Leia Organa)", "CC-1119 \"Appo\"", "CC-2224 \"Cody\"",
        "CT-21-0408 \"Echo\"", "Cad Bane", "Cal Kestis", "Captain Drogan", "Captain Rex",
        "Captain Tarpals", "Cara Dune", "Chewbacca", "Chopper", "Commander Luke Skywalker",
        "Coruscant Underworld Police", "Count Dooku", "Crosshair (Scarred)", "Dark Trooper Moff Gideon", "Darth Bane",
        "Darth Malak", "Darth Malgus", "Darth Revan", "Darth Vader", "Dash Rendar",
        "Dathcha", "Death Trooper", "Death Trooper (Peridea)", "Dengar", "Director Krennic",
        "Disguised Clone Trooper", "Doctor Aphra", "Droideka", "Eeth Koth", "Emperor Palpatine",
        "Enfys Nest", "Ezra Bridger (Exile)", "Fifth Brother", "Finn", "First Order SF TIE Pilot",
        "Garazeb \"Zeb\" Orrelios", "General Grievous", "General Syndulla", "Grand Admiral Thrawn", "Grand Master Yoda",
        "Great Mothers", "Greedo", "Han Solo", "Hoth Rebel Scout", "Hunter",
        "Huyang", "IG-100 MagnaGuard", "IG-12 & Grogu", "Iden Versio", "Jabba the Hutt",
        "Jar Jar Binks", "Jawa", "Jedi Knight Cal Kestis", "Jedi Knight Luke Skywalker", "Jedi Knight Revan",
        "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Jocasta Nu", "Juhani", "Jyn Erso",
        "Kuiil", "Kylo Ren", "Kylo Ren (Unmasked)", "Leia Organa", "Lord Vader",
        "Luke Skywalker (Farmboy)", "Mace Windu", "Mara Jade, The Emperor's Hand", "Master Qui-Gon", "Maul",
        "Merrin", "Night Trooper", "Nightsister Spirit", "Ninth Sister", "Old Daka",
        "Omega (Fugitive)", "Padmé Amidala", "Princess Kneesaa", "R2-D2", "RC-1262 \"Scorch\"",
        "Resistance Hero Poe", "Rey", "Rose Tico", "Royal Guard", "Saw Gerrera",
        "Second Sister", "Shin Hati", "Sith Assassin", "Sith Eternal Emperor", "Sith Trooper",
        "Starkiller", "Supreme Leader Kylo Ren", "Tarfful", "Taron Malicos", "Tech",
        "Third Sister", "Tusken Chieftain", "URoRRuR'R'R", "Ugnaught", "Veteran Smuggler Chewbacca",
        "Veteran Smuggler Han Solo", "Wampa", "Wrecker", "Zorii Bliss",
    ],
    "Summon": [
        "ARC Trooper", "CC-1119 \"Appo\"", "Doctor Aphra", "Geonosian Brood Alpha", "Luthen Rael",
        "Mon Mothma", "Queen Amidala",
    ],
    "Target Lock": [
        "0-0-0", "50R-T", "B1 Battle Droid", "B2 Super Battle Droid", "BT-1",
        "Doctor Aphra", "Droideka", "General Grievous", "Gungan Boomadier", "Hunter",
        "IG-100 MagnaGuard", "IG-88", "Imperial Probe Droid", "Kelleran Beq", "Lobot",
        "Omega", "Poggle the Lesser", "STAP", "Sana Starros", "T3-M4",
        "Tech", "Wrecker",
    ],
    "Taunt": [
        "Admiral Raddus", "Ahsoka Tano", "Ahsoka Tano (Fulcrum)", "Amilyn Holdo", "BB-8",
        "Bastila Shan", "Batcher", "Baylan Skoll", "Baze Malbus", "Ben Solo",
        "Bo-Katan (Mand'alor)", "Bo-Katan Kryze", "Boba Fett", "Boba Fett, Scion of Jango", "Boss Nass",
        "Bossk", "CT-21-0408 \"Echo\"", "CT-5555 \"Fives\"", "CX-2", "Canderous Ordo",
        "Captain Enoch", "Captain Tarpals", "Cara Dune", "Chief Nebit", "Chopper",
        "Clone Wars Chewbacca", "Commander Luke Skywalker", "Dark Trooper Moff Gideon", "Darth Bane", "Darth Malak",
        "Darth Malgus", "Darth Maul", "Darth Sion", "Darth Talon", "Darth Vader",
        "Director Krennic", "Eighth Brother", "Enfys Nest", "Fennec Shand", "Finn",
        "First Order Stormtrooper", "Gamorrean Guard", "General Kenobi", "General Skywalker", "General Syndulla",
        "Geonosian Brood Alpha", "Grand Inquisitor", "Grand Master Yoda", "Great Mothers", "Gungan Phalanx",
        "Han Solo", "Hoth Rebel Soldier", "Hunter", "IG-100 MagnaGuard", "IG-11",
        "Imperial Probe Droid", "Jabba the Hutt", "Jango Fett", "Jedi Knight Cal Kestis", "Jedi Knight Revan",
        "Jedi Master Kenobi", "Jedi Master Luke Skywalker", "Juhani", "Jyn Erso", "K-2SO",
        "Kanan Jarrus", "Krrsantan", "Kylo Ren (Unmasked)", "L3-37", "Leia Organa",
        "Lord Vader", "Luthen Rael", "Mace Windu", "Master Qui-Gon", "Maul",
        "Merrin", "Moff Gideon", "Mon Mothma", "Morgan Elsbeth", "Nightsister Zombie",
        "Ninth Sister", "Obi-Wan Kenobi (Old Ben)", "Omega", "Paploo", "Paz Vizsla",
        "Poe Dameron", "Queen Amidala", "RC-1262 \"Scorch\"", "Resistance Hero Finn", "Rey (Dark Side Vision)",
        "Royal Guard", "SM-33", "Sana Starros", "Savage Opress", "Saw Gerrera",
        "Scarif Rebel Pathfinder", "Shaak Ti", "Shin Hati", "Shoretrooper", "Sith Empire Trooper",
        "Sith Eternal Emperor", "Starkiller", "Stormtrooper", "Stormtrooper Han", "Sun Fac",
        "Supreme Leader Kylo Ren", "Tarfful", "Taron Malicos", "The Mandalorian (Beskar Armor)", "Third Sister",
        "Tusken Raider", "Wat Tambor", "Wrecker", "Wrecker (Mercenary)", "Zaalbar",
        "Zorii Bliss",
    ],
    "Tenacity Down": [
        "BB-8", "Boba Fett, Scion of Jango", "Cal Kestis", "Canderous Ordo", "Captain Rex",
        "Chewbacca", "Commander Luke Skywalker", "Count Dooku", "Darth Malak", "Darth Traya",
        "Death Trooper (Peridea)", "Dengar", "Director Krennic", "Fifth Brother", "Geonosian Soldier",
        "Great Mothers", "Gungan Phalanx", "HK-47", "IG-11", "Jawa Scavenger",
        "Jedi Master Luke Skywalker", "Jocasta Nu", "Kylo Ren (Unmasked)", "Leia Organa", "Mara Jade, The Emperor's Hand",
        "Marrok", "Master Qui-Gon", "Nightsister Zombie", "Padawan Obi-Wan", "Queen Amidala",
        "Sana Starros", "TIE Fighter Pilot", "Wrecker (Mercenary)",
    ],
    "Tenacity Up": [
        "50R-T", "Admiral Ackbar", "Admiral Trench", "Ahsoka Tano", "Baylan Skoll",
        "Bo-Katan (Mand'alor)", "Bo-Katan Kryze", "Boba Fett, Scion of Jango", "CT-7567 \"Rex\"", "Captain Rex",
        "Cassian Andor", "Cere Junda", "Chirrut Îmwe", "Dengar", "Disguised Clone Trooper",
        "Droideka", "Enfys Nest", "Ezra Bridger (Exile)", "Fennec Shand", "First Order Officer",
        "Garazeb \"Zeb\" Orrelios", "General Syndulla", "Grand Inquisitor", "Grand Master Yoda", "Greef Karga",
        "Huyang", "Jar Jar Binks", "Jedi Knight Revan", "Jedi Master Kenobi", "Jedi Master Luke Skywalker",
        "Kelleran Beq", "L3-37", "Logray", "Luminara Unduli", "Master Qui-Gon",
        "Morgan Elsbeth", "Omega (Fugitive)", "Padawan Obi-Wan", "Princess Leia", "Queen Amidala",
        "Rose Tico", "SM-33", "Sana Starros", "Saw Gerrera", "Shaak Ti",
        "Sith Assassin", "Tarfful", "Tech", "The Mandalorian (Beskar Armor)", "Wrecker",
        "Zorii Bliss",
    ],
    "Thermal Detonator": [
        "Boba Fett", "Boushh (Leia Organa)", "Cad Bane", "Chief Nebit", "Dengar",
        "Gamorrean Guard", "Greedo", "Jabba the Hutt", "Jawa Engineer", "Jawa Scavenger",
        "Lord Vader", "Mob Enforcer", "Zam Wesell",
    ],
    "Torture": [
        "0-0-0", "Grand Inquisitor",
    ],
    "Unique: +Speed": [
        "Admiral Trench", "Ahsoka Tano", "Ahsoka Tano (Fulcrum)", "Ahsoka Tano (Snips)", "Amilyn Holdo",
        "Asajj Ventress", "BT-1", "Batcher", "Baylan Skoll", "Ben Solo",
        "Bo-Katan (Mand'alor)", "Boba Fett", "Boss Nass", "Boushh (Leia Organa)", "C-3PO",
        "CC-1119 \"Appo\"", "CT-5555 \"Fives\"", "CT-7567 \"Rex\"", "Captain Rex", "Darth Bane",
        "Darth Sidious", "Darth Talon", "Darth Vader", "Death Trooper (Peridea)", "Dengar",
        "Doctor Aphra", "Droideka", "Ezra Bridger (Exile)", "First Order TIE Pilot", "General Syndulla",
        "Grand Admiral Thrawn", "Grand Inquisitor", "Hondo Ohnaka", "Hunter (Mercenary)", "Jar Jar Binks",
        "Jawa Engineer", "Jedi Knight Luke Skywalker", "Jocasta Nu", "Juhani", "Jyn Erso",
        "Ki-Adi-Mundi", "Krrsantan", "Kylo Ren", "Lobot", "Lord Vader",
        "Luthen Rael", "Mace Windu", "Master Qui-Gon", "Merrin", "Mob Enforcer",
        "Mon Mothma", "Night Trooper", "Nightsister Zombie", "Nute Gunray", "Obi-Wan Kenobi (Old Ben)",
        "Omega", "Omega (Fugitive)", "Padawan Obi-Wan", "Padawan Sabine Wren", "Paploo",
        "Poggle the Lesser", "Princess Kneesaa", "Queen Amidala", "RC-1262 \"Scorch\"", "Rey (Dark Side Vision)",
        "SM-33", "STAP", "Sana Starros", "Savage Opress", "Scarif Rebel Pathfinder",
        "Scout Trooper", "Second Sister", "Seventh Sister", "Shin Hati", "Skiff Guard (Lando Calrissian)",
        "Starkiller", "Tarfful", "Tech", "Third Sister", "Tusken Raider",
        "Wedge Antilles", "Zaalbar", "Zam Wesell", "Zorii Bliss",
    ],
    "Vulnerable": [
        "Bo-Katan Kryze", "Boss Nass", "CX-2", "Eighth Brother", "Fifth Brother",
        "Grand Inquisitor", "Great Mothers", "Gungan Phalanx", "Iden Versio", "Jedi Knight Luke Skywalker",
        "Jedi Master Kenobi", "Jocasta Nu", "Leia Organa", "Mara Jade, The Emperor's Hand", "Mob Enforcer",
        "Morgan Elsbeth", "Night Trooper", "Queen Amidala", "Resistance Hero Poe", "Sana Starros",
        "Savage Opress", "Shin Hati", "Starkiller", "Taron Malicos",
    ],
}