

character_names = [
"0-0-0",
"50R-T",
"ARC Trooper",
"Aayla Secura",
"Admiral Ackbar",
"Admiral Piett",
"Admiral Raddus",
"Admiral Trench",
"Ahsoka Tano",
"Ahsoka Tano (Fulcrum)",
"Ahsoka Tano (Snips)",
"Amilyn Holdo",
"Asajj Ventress",
"Aurra Sing",
"B1 Battle Droid",
"B2 Super Battle Droid",
"BB-8",
"BT-1",
"Barriss Offee",
"Bastila Shan",
"Bastila Shan (Fallen)",
"Batcher",
"Baylan Skoll",
"Baze Malbus",
"Ben Solo",
"Biggs Darklighter",
"Bistan",
"Bo-Katan (Mand'alor)",
"Bo-Katan Kryze",
"Boba Fett",
"Boba Fett, Scion of Jango",
"Bodhi Rook",
"Boss Nass",
"Bossk",
"Boushh (Leia Organa)",
"C-3PO",
"CC-1119 'Appo'",
"CC-2224 'Cody'",
"CT-21-0408 'Echo'",
"CT-5555 'Fives'",
"CT-7567 'Rex'",
"CX-2",
"Cad Bane",
"Cal Kestis",
"Canderous Ordo",
"Captain Drogan",
"Captain Enoch",
"Captain Han Solo",
"Captain Phasma",
"Captain Rex",
"Captain Tarpals",
"Cara Dune",
"Carth Onasi",
"Cassian Andor",
"Cere Junda",
"Chewbacca",
"Chief Chirpa",
"Chief Nebit",
"Chirrut Îmwe",
"Chopper",
"Clone Sergeant - Phase I",
"Clone Wars Chewbacca",
"Colonel Starck",
"Commander Ahsoka Tano",
"Commander Luke Skywalker",
"Coruscant Underworld Police",
"Count Dooku",
"Crosshair (Scarred)",
"Dark Trooper",
"Dark Trooper Moff Gideon",
"Darth Bane",
"Darth Malak",
"Darth Malgus",
"Darth Maul",
"Darth Nihilus",
"Darth Revan",
"Darth Sidious",
"Darth Sion",
"Darth Talon",
"Darth Traya",
"Darth Vader",
"Dash Rendar",
"Dathcha",
"Death Trooper",
"Death Trooper (Peridea)",
"Dengar",
"Director Krennic",
"Disguised Clone Trooper",
"Doctor Aphra",
"Droideka",
"Echo",
"Eeth Koth",
"Eighth Brother",
"Embo",
"Emperor Palpatine",
"Enfys Nest",
"Ewok Elder",
"Ewok Scout",
"Ezra Bridger",
"Ezra Bridger (Exile)",
"Fennec Shand",
"Fifth Brother",
"Finn",
"First Order Executioner",
"First Order Officer",
"First Order SF TIE Pilot",
"First Order Stormtrooper",
"First Order TIE Pilot",
"Gamorrean Guard",
"Gar Saxon",
"Garazeb 'Zeb' Orrelios",
"General Grievous",
"General Hux",
"General Kenobi",
"General Skywalker",
"General Syndulla",
"General Veers",
"Geonosian Brood Alpha",
"Geonosian Soldier",
"Geonosian Spy",
"Grand Admiral Thrawn",
"Grand Inquisitor",
"Grand Master Yoda",
"Grand Moff Tarkin",
"Great Mothers",
"Greedo",
"Greef Karga",
"Gungan Boomadier",
"Gungan Phalanx",
"HK-47",
"Han Solo",
"Hera Syndulla",
"Hermit Yoda",
"Hondo Ohnaka",
"Hoth Rebel Scout",
"Hoth Rebel Soldier",
"Hunter",
"Hunter (Mercenary)",
"Huyang",
"IG-100 MagnaGuard",
"IG-11",
"IG-12 & Grogu",
"IG-86 Sentinel Droid",
"IG-88",
"Iden Versio",
"Ima-Gun Di",
"Imperial Probe Droid",
"Imperial Super Commando",
"Jabba the Hutt",
"Jango Fett",
"Jar Jar Binks",
"Jawa",
"Jawa Engineer",
"Jawa Scavenger",
"Jedi Consular",
"Jedi Knight Anakin",
"Jedi Knight Cal Kestis",
"Jedi Knight Guardian",
"Jedi Knight Luke Skywalker",
"Jedi Knight Revan",
"Jedi Master Kenobi",
"Jedi Master Luke Skywalker",
"Jocasta Nu",
"Jolee Bindo",
"Juhani",
"Jyn Erso",
"K-2SO",
"Kanan Jarrus",
"Kelleran Beq",
"Ki-Adi-Mundi",
"Kit Fisto",
"Krrsantan",
"Kuiil",
"Kyle Katarn",
"Kylo Ren",
"Kylo Ren (Unmasked)",
"L3-37",
"Lando Calrissian",
"Leia Organa",
"Lobot",
"Logray",
"Lord Vader",
"Luke Skywalker (Farmboy)",
"Luminara Unduli",
"Luthen Rael",
"Mace Windu",
"Magmatrooper",
"Mara Jade, The Emperor's Hand",
"Marrok",
"Master Qui-Gon",
"Maul",
"Merrin",
"Mission Vao",
"Mob Enforcer",
"Moff Gideon",
"Mon Mothma",
"Morgan Elsbeth",
"Mother Talzin",
"Night Trooper",
"Nightsister Acolyte",
"Nightsister Initiate",
"Nightsister Spirit",
"Nightsister Zombie",
"Ninth Sister",
"Nute Gunray",
"Obi-Wan Kenobi (Old Ben)",
"Old Daka",
"Omega",
"Omega (Fugitive)",
"Padawan Obi-Wan",
"Padawan Sabine Wren",
"Padmé Amidala",
"Pao",
"Paploo",
"Paz Vizsla",
"Plo Koon",
"Poe Dameron",
"Poggle the Lesser",
"Princess Kneesaa",
"Princess Leia",
"Qi'ra",
"Queen Amidala",
"Qui-Gon Jinn",
"R2-D2",
"Range Trooper",
"Rebel Officer Leia Organa",
"Resistance Hero Finn",
"Resistance Hero Poe",
"Resistance Pilot",
"Resistance Trooper",
"Rey",
"Rey (Dark Side Vision)",
"Rey (Jedi Training)",
"Rey (Scavenger)",
"Rose Tico",
"Royal Guard",
"SM-33",
"STAP",
"Sabine Wren",
"Sana Starros",
"Savage Opress",
"Saw Gerrera",
"Scarif Rebel Pathfinder",
"Scout Trooper",
"Second Sister",
"Seventh Sister",
"Shaak Ti",
"Shin Hati",
"Shoretrooper",
"Sith Assassin",
"Sith Empire Trooper",
"Sith Eternal Emperor",
"Sith Marauder",
"Sith Trooper",
"Skiff Guard (Lando Calrissian)",
"Snowtrooper",
"Starkiller",
"Stormtrooper",
"Stormtrooper Han",
"Sun Fac",
"Supreme Leader Kylo Ren",
"T3-M4",
"TIE Fighter Pilot",
"Talia",
"Tarfful",
"Taron Malicos",
"Tech",
"Teebo",
"The Armorer",
"The Mandalorian",
"The Mandalorian (Beskar Armor)",
"Third Sister",
"Threepio & Chewie",
"Tusken Chieftain",
"Tusken Raider",
"Tusken Shaman",
"Tusken Warrior",
"URoRRuR'R'R",
"Ugnaught",
"Vandor Chewbacca",
"Veteran Smuggler Chewbacca",
"Veteran Smuggler Han Solo",
"Visas Marr",
"Wampa",
"Wat Tambor",
"Wedge Antilles",
"Wicket",
"Wrecker",
"Wrecker (Mercenary)",
"Young Han Solo",
"Young Lando Calrissian",
"Zaalbar",
"Zam Wesell",
"Zorii Bliss"]

Salvage = ["Carbonite circuit board", "Bronzium wiring", "Chromium transistor", "Aurodium heatsink",
           "Electrium conductor", "Zinbiddle card", "Impulse detector", "Aeromagnifier",
           "Gyrda keypad", "Droid brain"]

Signal_Data = ["Fragmented [light blue]", "Incomplete [green]", "Flawed [dark blue]"]

salvage_reqs = [
    [40, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # R0
    [30, 40, 0, 0, 0, 0, 0, 0, 0, 0],  # R1
    [30, 40, 0, 0, 0, 0, 0, 0, 0, 0],  # R2
    [30, 40, 40, 0, 0, 0, 0, 0, 0, 0],  # R3
    [30, 40, 30, 20, 0, 0, 0, 0, 0, 0],  # R4
    [20, 30, 30, 20, 20, 0, 0, 0, 0, 0],  # R5
    [20, 30, 20, 20, 20, 10, 0, 0, 0, 0],  # R6
    [0, 0, 20, 20, 20, 20, 20, 20, 0, 0],  # R7
    [0, 0, 20, 20, 20, 20, 20, 20, 20, 20],  # R8
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # R9
]

signalData_reqs = [
    [0, 0, 0], [15, 0, 0], [20, 15, 0], [20, 25, 0],
    [20, 25, 15], [20, 25, 25], [20, 25, 35], [20, 25, 45],
    [30, 30, 55], [0, 0, 0]
]